debug: false
# server common
server:
  port: 8088
  servlet:
    context-path: /demo
# spring common
spring:
  application:
    name: demo-intergrate
# dubbox
dubbox:
  application:
    name: ${spring.application.name}
    organization: jjs
    owner: demo-intergrate
  registry:
    protocol: zookeeper
    address: 172.16.4.114:2181
  protocol:
    name: dubbo
    serialization: hessian2
    accesslog: dubbo.accesslog
    port: 20881
  scan: com.myjava.demo.intergrate
# 天眼查配置
tyc:
  # 根据信用代码组织机构代码获取公司信息接口
  i736:
    id:     736
    name:   根据信用代码组织机构代码获取公司信息
    descr:  根据信用代码组织机构代码/组织机构代码/注册号获取公司信息
    url:    http://open.api.tianyancha.com/services/v4/open/getCompanyByCode
    token:  97740505-087e-4494-a001-85a4e10a5685
    method: GET


