package com.leyoujia.coa.zc.mall.dao.erp.entity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   人力资源_员工表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table HR_WORKER
 */
public class HrWorker implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.ID")
    private Integer id;

    /**
     * Database Column Remarks:
     *   员工ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_ID")
    private String workerId;

    /**
     * Database Column Remarks:
     *   员工姓名
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_NAME")
    private String workerName;

    /**
     * Database Column Remarks:
     *   姓名简写
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_SPELL")
    private String workerSpell;

    /**
     * Database Column Remarks:
     *   性别 1=男 2=女
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.SEX")
    private String sex;

    /**
     * Database Column Remarks:
     *   部门ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.DEPT_ID")
    private Integer deptId;

    /**
     * Database Column Remarks:
     *   职务ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.DUTY_ID")
    private Integer dutyId;

    /**
     * Database Column Remarks:
     *   房源类型管控 与全局常量字典 房源用途一致
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.RESPON_AREA")
    private String responArea;

    /**
     * Database Column Remarks:
     *   管控部门属性 1全部，2 部门，3 自定义
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.MANAGE_CTRL")
    private Integer manageCtrl;

    /**
     * Database Column Remarks:
     *   权限定义 0=来自职务  1 = 自定义
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.RIGHT_TYPE")
    private Integer rightType;

    /**
     * Database Column Remarks:
     *   是否跨公司
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.ISSPAN")
    private Integer isspan;

    /**
     * Database Column Remarks:
     *   看业主数 0=无限制
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.SEE_OWNER_COUNT")
    private Integer seeOwnerCount;

    /**
     * Database Column Remarks:
     *   EMAIL
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.EMAIL")
    private String email;

    /**
     * Database Column Remarks:
     *   MSN
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.MSN")
    private String msn;

    /**
     * Database Column Remarks:
     *   电话
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.PHONE")
    private String phone;

    /**
     * Database Column Remarks:
     *   短号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.SHORTNO")
    private String shortno;

    /**
     * Database Column Remarks:
     *   上级领导ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.MANAGER_ID")
    private String managerId;

    /**
     * Database Column Remarks:
     *    登录密码
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_PWD")
    private String workerPwd;

    /**
     * Database Column Remarks:
     *   员工工号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_NO")
    private String workerNo;

    /**
     * Database Column Remarks:
     *   员工状态
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_STATUS")
    private Integer workerStatus;

    /**
     * Database Column Remarks:
     *   登录状态
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.LOGIN_STATUS")
    private String loginStatus;

    /**
     * Database Column Remarks:
     *   档案审核 Y=已审核
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.ARCHIVES_STATUS")
    private String archivesStatus;

    /**
     * Database Column Remarks:
     *   纸质资料状态(0待交入职资料1已交入职资料2待交离职资料3已交离职资料)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.PAPER_DATA_STATUS")
    private Integer paperDataStatus;

    /**
     * Database Column Remarks:
     *   业绩查看  属性 1全部，2 部门，3 自定义
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.GRADE_CTRL")
    private Integer gradeCtrl;

    /**
     * Database Column Remarks:
     *   类型 3=转正 2= 试用 0 = 见习
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.EMPTYPE")
    private Integer emptype;

    /**
     * Database Column Remarks:
     *   电话
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.PHONE_TEL")
    private String phoneTel;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.HEAD_PIC")
    private String headPic;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_DESC")
    private String workerDesc;

    /**
     * Database Column Remarks:
     *   见习岗位
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.STUDY_DUTY_ID")
    private String studyDutyId;

    /**
     * Database Column Remarks:
     *   身份证号码
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.ID_CARD")
    private String idCard;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.HR_UUID")
    private String hrUuid;

    /**
     * Database Column Remarks:
     *   是否有网站后台权限
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.SITE_PUR")
    private Byte sitePur;

    /**
     * Database Column Remarks:
     *   增量时间标识
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.BI_DATE")
    private Date biDate;

    /**
     * Database Column Remarks:
     *   管控部门列表
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.MANAGE_AREA_ID")
    private String manageAreaId;

    /**
     * Database Column Remarks:
     *   业绩范围列表
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.GRADE_AREA_ID")
    private String gradeAreaId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: HR_WORKER")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_ID")
    public String getWorkerId() {
        return workerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_ID")
    public void setWorkerId(String workerId) {
        this.workerId = workerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_NAME")
    public String getWorkerName() {
        return workerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_NAME")
    public void setWorkerName(String workerName) {
        this.workerName = workerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_SPELL")
    public String getWorkerSpell() {
        return workerSpell;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_SPELL")
    public void setWorkerSpell(String workerSpell) {
        this.workerSpell = workerSpell;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.SEX")
    public String getSex() {
        return sex;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.SEX")
    public void setSex(String sex) {
        this.sex = sex;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.DEPT_ID")
    public Integer getDeptId() {
        return deptId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.DEPT_ID")
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.DUTY_ID")
    public Integer getDutyId() {
        return dutyId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.DUTY_ID")
    public void setDutyId(Integer dutyId) {
        this.dutyId = dutyId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.RESPON_AREA")
    public String getResponArea() {
        return responArea;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.RESPON_AREA")
    public void setResponArea(String responArea) {
        this.responArea = responArea;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.MANAGE_CTRL")
    public Integer getManageCtrl() {
        return manageCtrl;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.MANAGE_CTRL")
    public void setManageCtrl(Integer manageCtrl) {
        this.manageCtrl = manageCtrl;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.RIGHT_TYPE")
    public Integer getRightType() {
        return rightType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.RIGHT_TYPE")
    public void setRightType(Integer rightType) {
        this.rightType = rightType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.ISSPAN")
    public Integer getIsspan() {
        return isspan;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.ISSPAN")
    public void setIsspan(Integer isspan) {
        this.isspan = isspan;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.SEE_OWNER_COUNT")
    public Integer getSeeOwnerCount() {
        return seeOwnerCount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.SEE_OWNER_COUNT")
    public void setSeeOwnerCount(Integer seeOwnerCount) {
        this.seeOwnerCount = seeOwnerCount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.EMAIL")
    public String getEmail() {
        return email;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.EMAIL")
    public void setEmail(String email) {
        this.email = email;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.MSN")
    public String getMsn() {
        return msn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.MSN")
    public void setMsn(String msn) {
        this.msn = msn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.PHONE")
    public String getPhone() {
        return phone;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.PHONE")
    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.SHORTNO")
    public String getShortno() {
        return shortno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.SHORTNO")
    public void setShortno(String shortno) {
        this.shortno = shortno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.MANAGER_ID")
    public String getManagerId() {
        return managerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.MANAGER_ID")
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_PWD")
    public String getWorkerPwd() {
        return workerPwd;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_PWD")
    public void setWorkerPwd(String workerPwd) {
        this.workerPwd = workerPwd;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_NO")
    public String getWorkerNo() {
        return workerNo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_NO")
    public void setWorkerNo(String workerNo) {
        this.workerNo = workerNo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_STATUS")
    public Integer getWorkerStatus() {
        return workerStatus;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_STATUS")
    public void setWorkerStatus(Integer workerStatus) {
        this.workerStatus = workerStatus;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.LOGIN_STATUS")
    public String getLoginStatus() {
        return loginStatus;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.LOGIN_STATUS")
    public void setLoginStatus(String loginStatus) {
        this.loginStatus = loginStatus;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.ARCHIVES_STATUS")
    public String getArchivesStatus() {
        return archivesStatus;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.ARCHIVES_STATUS")
    public void setArchivesStatus(String archivesStatus) {
        this.archivesStatus = archivesStatus;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.PAPER_DATA_STATUS")
    public Integer getPaperDataStatus() {
        return paperDataStatus;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.PAPER_DATA_STATUS")
    public void setPaperDataStatus(Integer paperDataStatus) {
        this.paperDataStatus = paperDataStatus;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.GRADE_CTRL")
    public Integer getGradeCtrl() {
        return gradeCtrl;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.GRADE_CTRL")
    public void setGradeCtrl(Integer gradeCtrl) {
        this.gradeCtrl = gradeCtrl;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.EMPTYPE")
    public Integer getEmptype() {
        return emptype;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.EMPTYPE")
    public void setEmptype(Integer emptype) {
        this.emptype = emptype;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.PHONE_TEL")
    public String getPhoneTel() {
        return phoneTel;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.PHONE_TEL")
    public void setPhoneTel(String phoneTel) {
        this.phoneTel = phoneTel;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.HEAD_PIC")
    public String getHeadPic() {
        return headPic;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.HEAD_PIC")
    public void setHeadPic(String headPic) {
        this.headPic = headPic;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_DESC")
    public String getWorkerDesc() {
        return workerDesc;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.WORKER_DESC")
    public void setWorkerDesc(String workerDesc) {
        this.workerDesc = workerDesc;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.STUDY_DUTY_ID")
    public String getStudyDutyId() {
        return studyDutyId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.STUDY_DUTY_ID")
    public void setStudyDutyId(String studyDutyId) {
        this.studyDutyId = studyDutyId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.ID_CARD")
    public String getIdCard() {
        return idCard;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.ID_CARD")
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.HR_UUID")
    public String getHrUuid() {
        return hrUuid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.HR_UUID")
    public void setHrUuid(String hrUuid) {
        this.hrUuid = hrUuid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.SITE_PUR")
    public Byte getSitePur() {
        return sitePur;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.SITE_PUR")
    public void setSitePur(Byte sitePur) {
        this.sitePur = sitePur;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.BI_DATE")
    public Date getBiDate() {
        return biDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.BI_DATE")
    public void setBiDate(Date biDate) {
        this.biDate = biDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.MANAGE_AREA_ID")
    public String getManageAreaId() {
        return manageAreaId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.MANAGE_AREA_ID")
    public void setManageAreaId(String manageAreaId) {
        this.manageAreaId = manageAreaId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.GRADE_AREA_ID")
    public String getGradeAreaId() {
        return gradeAreaId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: HR_WORKER.GRADE_AREA_ID")
    public void setGradeAreaId(String gradeAreaId) {
        this.gradeAreaId = gradeAreaId;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: HR_WORKER")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", workerId=").append(workerId);
        sb.append(", workerName=").append(workerName);
        sb.append(", workerSpell=").append(workerSpell);
        sb.append(", sex=").append(sex);
        sb.append(", deptId=").append(deptId);
        sb.append(", dutyId=").append(dutyId);
        sb.append(", responArea=").append(responArea);
        sb.append(", manageCtrl=").append(manageCtrl);
        sb.append(", rightType=").append(rightType);
        sb.append(", isspan=").append(isspan);
        sb.append(", seeOwnerCount=").append(seeOwnerCount);
        sb.append(", email=").append(email);
        sb.append(", msn=").append(msn);
        sb.append(", phone=").append(phone);
        sb.append(", shortno=").append(shortno);
        sb.append(", managerId=").append(managerId);
        sb.append(", workerPwd=").append(workerPwd);
        sb.append(", workerNo=").append(workerNo);
        sb.append(", workerStatus=").append(workerStatus);
        sb.append(", loginStatus=").append(loginStatus);
        sb.append(", archivesStatus=").append(archivesStatus);
        sb.append(", paperDataStatus=").append(paperDataStatus);
        sb.append(", gradeCtrl=").append(gradeCtrl);
        sb.append(", emptype=").append(emptype);
        sb.append(", phoneTel=").append(phoneTel);
        sb.append(", headPic=").append(headPic);
        sb.append(", workerDesc=").append(workerDesc);
        sb.append(", studyDutyId=").append(studyDutyId);
        sb.append(", idCard=").append(idCard);
        sb.append(", hrUuid=").append(hrUuid);
        sb.append(", sitePur=").append(sitePur);
        sb.append(", biDate=").append(biDate);
        sb.append(", manageAreaId=").append(manageAreaId);
        sb.append(", gradeAreaId=").append(gradeAreaId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: HR_WORKER")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HrWorker other = (HrWorker) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getWorkerId() == null ? other.getWorkerId() == null : this.getWorkerId().equals(other.getWorkerId()))
            && (this.getWorkerName() == null ? other.getWorkerName() == null : this.getWorkerName().equals(other.getWorkerName()))
            && (this.getWorkerSpell() == null ? other.getWorkerSpell() == null : this.getWorkerSpell().equals(other.getWorkerSpell()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
            && (this.getDutyId() == null ? other.getDutyId() == null : this.getDutyId().equals(other.getDutyId()))
            && (this.getResponArea() == null ? other.getResponArea() == null : this.getResponArea().equals(other.getResponArea()))
            && (this.getManageCtrl() == null ? other.getManageCtrl() == null : this.getManageCtrl().equals(other.getManageCtrl()))
            && (this.getRightType() == null ? other.getRightType() == null : this.getRightType().equals(other.getRightType()))
            && (this.getIsspan() == null ? other.getIsspan() == null : this.getIsspan().equals(other.getIsspan()))
            && (this.getSeeOwnerCount() == null ? other.getSeeOwnerCount() == null : this.getSeeOwnerCount().equals(other.getSeeOwnerCount()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getMsn() == null ? other.getMsn() == null : this.getMsn().equals(other.getMsn()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getShortno() == null ? other.getShortno() == null : this.getShortno().equals(other.getShortno()))
            && (this.getManagerId() == null ? other.getManagerId() == null : this.getManagerId().equals(other.getManagerId()))
            && (this.getWorkerPwd() == null ? other.getWorkerPwd() == null : this.getWorkerPwd().equals(other.getWorkerPwd()))
            && (this.getWorkerNo() == null ? other.getWorkerNo() == null : this.getWorkerNo().equals(other.getWorkerNo()))
            && (this.getWorkerStatus() == null ? other.getWorkerStatus() == null : this.getWorkerStatus().equals(other.getWorkerStatus()))
            && (this.getLoginStatus() == null ? other.getLoginStatus() == null : this.getLoginStatus().equals(other.getLoginStatus()))
            && (this.getArchivesStatus() == null ? other.getArchivesStatus() == null : this.getArchivesStatus().equals(other.getArchivesStatus()))
            && (this.getPaperDataStatus() == null ? other.getPaperDataStatus() == null : this.getPaperDataStatus().equals(other.getPaperDataStatus()))
            && (this.getGradeCtrl() == null ? other.getGradeCtrl() == null : this.getGradeCtrl().equals(other.getGradeCtrl()))
            && (this.getEmptype() == null ? other.getEmptype() == null : this.getEmptype().equals(other.getEmptype()))
            && (this.getPhoneTel() == null ? other.getPhoneTel() == null : this.getPhoneTel().equals(other.getPhoneTel()))
            && (this.getHeadPic() == null ? other.getHeadPic() == null : this.getHeadPic().equals(other.getHeadPic()))
            && (this.getWorkerDesc() == null ? other.getWorkerDesc() == null : this.getWorkerDesc().equals(other.getWorkerDesc()))
            && (this.getStudyDutyId() == null ? other.getStudyDutyId() == null : this.getStudyDutyId().equals(other.getStudyDutyId()))
            && (this.getIdCard() == null ? other.getIdCard() == null : this.getIdCard().equals(other.getIdCard()))
            && (this.getHrUuid() == null ? other.getHrUuid() == null : this.getHrUuid().equals(other.getHrUuid()))
            && (this.getSitePur() == null ? other.getSitePur() == null : this.getSitePur().equals(other.getSitePur()))
            && (this.getBiDate() == null ? other.getBiDate() == null : this.getBiDate().equals(other.getBiDate()))
            && (this.getManageAreaId() == null ? other.getManageAreaId() == null : this.getManageAreaId().equals(other.getManageAreaId()))
            && (this.getGradeAreaId() == null ? other.getGradeAreaId() == null : this.getGradeAreaId().equals(other.getGradeAreaId()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: HR_WORKER")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getWorkerId() == null) ? 0 : getWorkerId().hashCode());
        result = prime * result + ((getWorkerName() == null) ? 0 : getWorkerName().hashCode());
        result = prime * result + ((getWorkerSpell() == null) ? 0 : getWorkerSpell().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        result = prime * result + ((getDutyId() == null) ? 0 : getDutyId().hashCode());
        result = prime * result + ((getResponArea() == null) ? 0 : getResponArea().hashCode());
        result = prime * result + ((getManageCtrl() == null) ? 0 : getManageCtrl().hashCode());
        result = prime * result + ((getRightType() == null) ? 0 : getRightType().hashCode());
        result = prime * result + ((getIsspan() == null) ? 0 : getIsspan().hashCode());
        result = prime * result + ((getSeeOwnerCount() == null) ? 0 : getSeeOwnerCount().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getMsn() == null) ? 0 : getMsn().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getShortno() == null) ? 0 : getShortno().hashCode());
        result = prime * result + ((getManagerId() == null) ? 0 : getManagerId().hashCode());
        result = prime * result + ((getWorkerPwd() == null) ? 0 : getWorkerPwd().hashCode());
        result = prime * result + ((getWorkerNo() == null) ? 0 : getWorkerNo().hashCode());
        result = prime * result + ((getWorkerStatus() == null) ? 0 : getWorkerStatus().hashCode());
        result = prime * result + ((getLoginStatus() == null) ? 0 : getLoginStatus().hashCode());
        result = prime * result + ((getArchivesStatus() == null) ? 0 : getArchivesStatus().hashCode());
        result = prime * result + ((getPaperDataStatus() == null) ? 0 : getPaperDataStatus().hashCode());
        result = prime * result + ((getGradeCtrl() == null) ? 0 : getGradeCtrl().hashCode());
        result = prime * result + ((getEmptype() == null) ? 0 : getEmptype().hashCode());
        result = prime * result + ((getPhoneTel() == null) ? 0 : getPhoneTel().hashCode());
        result = prime * result + ((getHeadPic() == null) ? 0 : getHeadPic().hashCode());
        result = prime * result + ((getWorkerDesc() == null) ? 0 : getWorkerDesc().hashCode());
        result = prime * result + ((getStudyDutyId() == null) ? 0 : getStudyDutyId().hashCode());
        result = prime * result + ((getIdCard() == null) ? 0 : getIdCard().hashCode());
        result = prime * result + ((getHrUuid() == null) ? 0 : getHrUuid().hashCode());
        result = prime * result + ((getSitePur() == null) ? 0 : getSitePur().hashCode());
        result = prime * result + ((getBiDate() == null) ? 0 : getBiDate().hashCode());
        result = prime * result + ((getManageAreaId() == null) ? 0 : getManageAreaId().hashCode());
        result = prime * result + ((getGradeAreaId() == null) ? 0 : getGradeAreaId().hashCode());
        return result;
    }
}