package com.leyoujia.coa.zc.mall.dao.erp.entity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   竞拍记录.
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table JHS_AUCTION_RECORD
 */
public class JhsAuctionRecord implements Serializable {
    /**
     * Database Column Remarks:
     *   id.
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.ID")
    private Integer id;

    /**
     * Database Column Remarks:
     *   商品id.
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.COMMODITY_ID")
    private Integer commodityId;

    /**
     * Database Column Remarks:
     *   商品标题.
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.COMMODITY_TITLE")
    private String commodityTitle;

    /**
     * Database Column Remarks:
     *   竞拍人id.
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.STAFF_ID")
    private String staffId;

    /**
     * Database Column Remarks:
     *   竞拍人姓名.
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.STAFF_NAME")
    private String staffName;

    /**
     * Database Column Remarks:
     *   竞拍后价格.
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.PRICE")
    private Double price;

    /**
     * Database Column Remarks:
     *   竞拍前价格.
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.PRE_PRICE")
    private Double prePrice;

    /**
     * Database Column Remarks:
     *   竞拍时间.
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.CREATE_DATE")
    private Date createDate;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_AUCTION_RECORD")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.COMMODITY_ID")
    public Integer getCommodityId() {
        return commodityId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.COMMODITY_ID")
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.COMMODITY_TITLE")
    public String getCommodityTitle() {
        return commodityTitle;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.COMMODITY_TITLE")
    public void setCommodityTitle(String commodityTitle) {
        this.commodityTitle = commodityTitle;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.STAFF_ID")
    public String getStaffId() {
        return staffId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.STAFF_ID")
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.STAFF_NAME")
    public String getStaffName() {
        return staffName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.STAFF_NAME")
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.PRICE")
    public Double getPrice() {
        return price;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.PRICE")
    public void setPrice(Double price) {
        this.price = price;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.PRE_PRICE")
    public Double getPrePrice() {
        return prePrice;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.PRE_PRICE")
    public void setPrePrice(Double prePrice) {
        this.prePrice = prePrice;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.CREATE_DATE")
    public Date getCreateDate() {
        return createDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_AUCTION_RECORD.CREATE_DATE")
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_AUCTION_RECORD")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", commodityId=").append(commodityId);
        sb.append(", commodityTitle=").append(commodityTitle);
        sb.append(", staffId=").append(staffId);
        sb.append(", staffName=").append(staffName);
        sb.append(", price=").append(price);
        sb.append(", prePrice=").append(prePrice);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_AUCTION_RECORD")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JhsAuctionRecord other = (JhsAuctionRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCommodityId() == null ? other.getCommodityId() == null : this.getCommodityId().equals(other.getCommodityId()))
            && (this.getCommodityTitle() == null ? other.getCommodityTitle() == null : this.getCommodityTitle().equals(other.getCommodityTitle()))
            && (this.getStaffId() == null ? other.getStaffId() == null : this.getStaffId().equals(other.getStaffId()))
            && (this.getStaffName() == null ? other.getStaffName() == null : this.getStaffName().equals(other.getStaffName()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getPrePrice() == null ? other.getPrePrice() == null : this.getPrePrice().equals(other.getPrePrice()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_AUCTION_RECORD")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCommodityId() == null) ? 0 : getCommodityId().hashCode());
        result = prime * result + ((getCommodityTitle() == null) ? 0 : getCommodityTitle().hashCode());
        result = prime * result + ((getStaffId() == null) ? 0 : getStaffId().hashCode());
        result = prime * result + ((getStaffName() == null) ? 0 : getStaffName().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getPrePrice() == null) ? 0 : getPrePrice().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        return result;
    }
}