package com.leyoujia.coa.zc.mall.dao.erp.entity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   公费订单分行成本记录表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table JHS_BRANCH_COST_LOG
 */
public class JhsBranchCostLog implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.ID")
    private Integer id;

    /**
     * Database Column Remarks:
     *   订单id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.ORDER_ID")
    private Integer orderId;

    /**
     * Database Column Remarks:
     *   操作记录
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.OPERTATION_LOG")
    private String opertationLog;

    /**
     * Database Column Remarks:
     *   状态 -1 无效 0 未进行处理 1 已经生成分行成本数据 2 进行了离职代扣以及分行成本扣减 3 购买人在职满三个月了不用再出来了
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.STATUS")
    private String status;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.CREATE_DATE")
    private Date createDate;

    /**
     * Database Column Remarks:
     *   更新时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.UPDATE_DATE")
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   时间戳标识
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.BI_DATE")
    private Date biDate;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_BRANCH_COST_LOG")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.ORDER_ID")
    public Integer getOrderId() {
        return orderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.ORDER_ID")
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.OPERTATION_LOG")
    public String getOpertationLog() {
        return opertationLog;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.OPERTATION_LOG")
    public void setOpertationLog(String opertationLog) {
        this.opertationLog = opertationLog;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.STATUS")
    public String getStatus() {
        return status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.STATUS")
    public void setStatus(String status) {
        this.status = status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.CREATE_DATE")
    public Date getCreateDate() {
        return createDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.CREATE_DATE")
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.UPDATE_DATE")
    public Date getUpdateDate() {
        return updateDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.UPDATE_DATE")
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.BI_DATE")
    public Date getBiDate() {
        return biDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_BRANCH_COST_LOG.BI_DATE")
    public void setBiDate(Date biDate) {
        this.biDate = biDate;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_BRANCH_COST_LOG")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", opertationLog=").append(opertationLog);
        sb.append(", status=").append(status);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", biDate=").append(biDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_BRANCH_COST_LOG")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JhsBranchCostLog other = (JhsBranchCostLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getOpertationLog() == null ? other.getOpertationLog() == null : this.getOpertationLog().equals(other.getOpertationLog()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getBiDate() == null ? other.getBiDate() == null : this.getBiDate().equals(other.getBiDate()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_BRANCH_COST_LOG")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getOpertationLog() == null) ? 0 : getOpertationLog().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getBiDate() == null) ? 0 : getBiDate().hashCode());
        return result;
    }
}