package com.leyoujia.coa.zc.mall.dao.erp.entity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   仓库商品表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table JHS_COMMODITY
 */
public class JhsCommodity implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.ID")
    private Integer id;

    /**
     * Database Column Remarks:
     *   名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.TITLE")
    private String title;

    /**
     * Database Column Remarks:
     *   类别id, 对应表JHS_SUBJECT
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CATEGORY_ID")
    private Integer categoryId;

    /**
     * Database Column Remarks:
     *   简称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SHORT_NAME")
    private String shortName;

    /**
     * Database Column Remarks:
     *   图片地址
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PHOTO_URL")
    private String photoUrl;

    /**
     * Database Column Remarks:
     *   数量
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.COUNT")
    private Integer count;

    /**
     * Database Column Remarks:
     *   规格
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.STANDARD")
    private String standard;

    /**
     * Database Column Remarks:
     *   型号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.MODEL_NO")
    private String modelNo;

    /**
     * Database Column Remarks:
     *   颜色
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.COLOR")
    private String color;

    /**
     * Database Column Remarks:
     *   尺寸
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SIZE")
    private String size;

    /**
     * Database Column Remarks:
     *   支付方式(0现金1现金和积分 废除)2支付宝3储备奖4顺豆
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PAY_METHOD")
    private String payMethod;

    /**
     * Database Column Remarks:
     *   竞拍时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.AUCTION_DATE")
    private Date auctionDate;

    /**
     * Database Column Remarks:
     *   起拍价格
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PRICE_START")
    private Double priceStart;

    /**
     * Database Column Remarks:
     *   跳拍价格
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PRICE_JUMP")
    private Double priceJump;

    /**
     * Database Column Remarks:
     *   市场价格
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.MARKET_PRICE")
    private Double marketPrice;

    /**
     * Database Column Remarks:
     *   定价
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PRICE")
    private Double price;

    /**
     * Database Column Remarks:
     *   发货时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.DELIVER_DATE")
    private Date deliverDate;

    /**
     * Database Column Remarks:
     *   发货方式
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.DELIVER_TYPE")
    private Integer deliverType;

    /**
     * Database Column Remarks:
     *   出售类型
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELL_TYPE")
    private Integer sellType;

    /**
     * Database Column Remarks:
     *   状态: 0待审核 1已审核 2未通过
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.STATUS")
    private Integer status;

    /**
     * Database Column Remarks:
     *   积分
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.INTEGRAL")
    private Integer integral;

    /**
     * Database Column Remarks:
     *   是否审核0-未 1-已审核通过
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_VERIFY")
    private Integer isVerify;

    /**
     * Database Column Remarks:
     *   发布日期
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CREATE_DATE")
    private Date createDate;

    /**
     * Database Column Remarks:
     *   拍卖结束时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.AUCTION_END_DATE")
    private Date auctionEndDate;

    /**
     * Database Column Remarks:
     *   员工id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.STAFF_ID")
    private String staffId;

    /**
     * Database Column Remarks:
     *   员工名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.STAFF_NAME")
    private String staffName;

    /**
     * Database Column Remarks:
     *   部门id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.DEPT_ID")
    private String deptId;

    /**
     * Database Column Remarks:
     *   部门名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.DEPT_NAME")
    private String deptName;

    /**
     * Database Column Remarks:
     *   是否下架，默认0，即上架
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_DOWN")
    private Integer isDown;

    /**
     * Database Column Remarks:
     *   是否手动下架 , 1是  2 否
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_MANUAL_DOWN")
    private Integer isManualDown;

    /**
     * Database Column Remarks:
     *   是否作为公司佣金,1-是|0-否
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_COMMISSION")
    private Integer isCommission;

    /**
     * Database Column Remarks:
     *   佣金公司编号，选择作为公司佣金则记录此项
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.COMMISSION_CM_NO")
    private String commissionCmNo;

    /**
     * Database Column Remarks:
     *   佣金公司名称，选择作为公司佣金则记录此项
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.COMMISSION_CM_NAME")
    private String commissionCmName;

    /**
     * Database Column Remarks:
     *   联系方式
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CONTACT")
    private String contact;

    /**
     * Database Column Remarks:
     *   审核备注
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CHECK_REMARKS")
    private String checkRemarks;

    /**
     * Database Column Remarks:
     *   拍卖封顶价格
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PRICE_MAX")
    private Double priceMax;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_WORKER_PAY")
    private Byte isWorkerPay;

    /**
     * Database Column Remarks:
     *   卖家姓名
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELLER_NAME")
    private String sellerName;

    /**
     * Database Column Remarks:
     *   卖家员工编号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELLER_WORKER_ID")
    private String sellerWorkerId;

    /**
     * Database Column Remarks:
     *   卖家手机
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELLER_PHONE")
    private String sellerPhone;

    /**
     * Database Column Remarks:
     *   卖家QQ
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELLER_QQ")
    private String sellerQq;

    /**
     * Database Column Remarks:
     *   获赠渠道 1开发商奖励 2其它
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_CHANNEL")
    private Byte givenChannel;

    /**
     * Database Column Remarks:
     *   获赠人员姓名
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_NAME")
    private String givenName;

    /**
     * Database Column Remarks:
     *   获赠人员员工编号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_WORKER_ID")
    private String givenWorkerId;

    /**
     * Database Column Remarks:
     *   获赠项目名
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_PROJECT")
    private String givenProject;

    /**
     * Database Column Remarks:
     *   获赠成交单号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_CJ_NUMBER")
    private String givenCjNumber;

    /**
     * Database Column Remarks:
     *   获赠项目id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_PROJECT_ID")
    private Integer givenProjectId;

    /**
     * Database Column Remarks:
     *   排序字段
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SORT_NUM")
    private Integer sortNum;

    /**
     * Database Column Remarks:
     *   房源网渠道
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CHANNEL_HOUSING_RESOURCES")
    private Integer channelHousingResources;

    /**
     * Database Column Remarks:
     *   乐办公渠道
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CHANNEL_HAPPY_OFFICE")
    private Integer channelHappyOffice;

    /**
     * Database Column Remarks:
     *   兑换条件 1：单次，2：多次
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.EXCHANGE_CONDITION")
    private Integer exchangeCondition;

    /**
     * Database Column Remarks:
     *   第三方兑换链接
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.EXCHANGE_THIRD_LINK")
    private String exchangeThirdLink;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_COMMODITY")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.TITLE")
    public String getTitle() {
        return title;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.TITLE")
    public void setTitle(String title) {
        this.title = title;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CATEGORY_ID")
    public Integer getCategoryId() {
        return categoryId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CATEGORY_ID")
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SHORT_NAME")
    public String getShortName() {
        return shortName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SHORT_NAME")
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PHOTO_URL")
    public String getPhotoUrl() {
        return photoUrl;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PHOTO_URL")
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.COUNT")
    public Integer getCount() {
        return count;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.COUNT")
    public void setCount(Integer count) {
        this.count = count;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.STANDARD")
    public String getStandard() {
        return standard;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.STANDARD")
    public void setStandard(String standard) {
        this.standard = standard;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.MODEL_NO")
    public String getModelNo() {
        return modelNo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.MODEL_NO")
    public void setModelNo(String modelNo) {
        this.modelNo = modelNo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.COLOR")
    public String getColor() {
        return color;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.COLOR")
    public void setColor(String color) {
        this.color = color;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SIZE")
    public String getSize() {
        return size;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SIZE")
    public void setSize(String size) {
        this.size = size;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PAY_METHOD")
    public String getPayMethod() {
        return payMethod;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PAY_METHOD")
    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.AUCTION_DATE")
    public Date getAuctionDate() {
        return auctionDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.AUCTION_DATE")
    public void setAuctionDate(Date auctionDate) {
        this.auctionDate = auctionDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PRICE_START")
    public Double getPriceStart() {
        return priceStart;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PRICE_START")
    public void setPriceStart(Double priceStart) {
        this.priceStart = priceStart;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PRICE_JUMP")
    public Double getPriceJump() {
        return priceJump;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PRICE_JUMP")
    public void setPriceJump(Double priceJump) {
        this.priceJump = priceJump;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.MARKET_PRICE")
    public Double getMarketPrice() {
        return marketPrice;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.MARKET_PRICE")
    public void setMarketPrice(Double marketPrice) {
        this.marketPrice = marketPrice;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PRICE")
    public Double getPrice() {
        return price;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PRICE")
    public void setPrice(Double price) {
        this.price = price;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.DELIVER_DATE")
    public Date getDeliverDate() {
        return deliverDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.DELIVER_DATE")
    public void setDeliverDate(Date deliverDate) {
        this.deliverDate = deliverDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.DELIVER_TYPE")
    public Integer getDeliverType() {
        return deliverType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.DELIVER_TYPE")
    public void setDeliverType(Integer deliverType) {
        this.deliverType = deliverType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELL_TYPE")
    public Integer getSellType() {
        return sellType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELL_TYPE")
    public void setSellType(Integer sellType) {
        this.sellType = sellType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.STATUS")
    public Integer getStatus() {
        return status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.STATUS")
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.INTEGRAL")
    public Integer getIntegral() {
        return integral;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.INTEGRAL")
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_VERIFY")
    public Integer getIsVerify() {
        return isVerify;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_VERIFY")
    public void setIsVerify(Integer isVerify) {
        this.isVerify = isVerify;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CREATE_DATE")
    public Date getCreateDate() {
        return createDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CREATE_DATE")
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.AUCTION_END_DATE")
    public Date getAuctionEndDate() {
        return auctionEndDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.AUCTION_END_DATE")
    public void setAuctionEndDate(Date auctionEndDate) {
        this.auctionEndDate = auctionEndDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.STAFF_ID")
    public String getStaffId() {
        return staffId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.STAFF_ID")
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.STAFF_NAME")
    public String getStaffName() {
        return staffName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.STAFF_NAME")
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.DEPT_ID")
    public String getDeptId() {
        return deptId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.DEPT_ID")
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.DEPT_NAME")
    public String getDeptName() {
        return deptName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.DEPT_NAME")
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_DOWN")
    public Integer getIsDown() {
        return isDown;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_DOWN")
    public void setIsDown(Integer isDown) {
        this.isDown = isDown;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_MANUAL_DOWN")
    public Integer getIsManualDown() {
        return isManualDown;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_MANUAL_DOWN")
    public void setIsManualDown(Integer isManualDown) {
        this.isManualDown = isManualDown;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_COMMISSION")
    public Integer getIsCommission() {
        return isCommission;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_COMMISSION")
    public void setIsCommission(Integer isCommission) {
        this.isCommission = isCommission;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.COMMISSION_CM_NO")
    public String getCommissionCmNo() {
        return commissionCmNo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.COMMISSION_CM_NO")
    public void setCommissionCmNo(String commissionCmNo) {
        this.commissionCmNo = commissionCmNo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.COMMISSION_CM_NAME")
    public String getCommissionCmName() {
        return commissionCmName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.COMMISSION_CM_NAME")
    public void setCommissionCmName(String commissionCmName) {
        this.commissionCmName = commissionCmName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CONTACT")
    public String getContact() {
        return contact;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CONTACT")
    public void setContact(String contact) {
        this.contact = contact;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CHECK_REMARKS")
    public String getCheckRemarks() {
        return checkRemarks;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CHECK_REMARKS")
    public void setCheckRemarks(String checkRemarks) {
        this.checkRemarks = checkRemarks;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PRICE_MAX")
    public Double getPriceMax() {
        return priceMax;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.PRICE_MAX")
    public void setPriceMax(Double priceMax) {
        this.priceMax = priceMax;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_WORKER_PAY")
    public Byte getIsWorkerPay() {
        return isWorkerPay;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.IS_WORKER_PAY")
    public void setIsWorkerPay(Byte isWorkerPay) {
        this.isWorkerPay = isWorkerPay;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELLER_NAME")
    public String getSellerName() {
        return sellerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELLER_NAME")
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELLER_WORKER_ID")
    public String getSellerWorkerId() {
        return sellerWorkerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELLER_WORKER_ID")
    public void setSellerWorkerId(String sellerWorkerId) {
        this.sellerWorkerId = sellerWorkerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELLER_PHONE")
    public String getSellerPhone() {
        return sellerPhone;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELLER_PHONE")
    public void setSellerPhone(String sellerPhone) {
        this.sellerPhone = sellerPhone;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELLER_QQ")
    public String getSellerQq() {
        return sellerQq;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SELLER_QQ")
    public void setSellerQq(String sellerQq) {
        this.sellerQq = sellerQq;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_CHANNEL")
    public Byte getGivenChannel() {
        return givenChannel;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_CHANNEL")
    public void setGivenChannel(Byte givenChannel) {
        this.givenChannel = givenChannel;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_NAME")
    public String getGivenName() {
        return givenName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_NAME")
    public void setGivenName(String givenName) {
        this.givenName = givenName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_WORKER_ID")
    public String getGivenWorkerId() {
        return givenWorkerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_WORKER_ID")
    public void setGivenWorkerId(String givenWorkerId) {
        this.givenWorkerId = givenWorkerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_PROJECT")
    public String getGivenProject() {
        return givenProject;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_PROJECT")
    public void setGivenProject(String givenProject) {
        this.givenProject = givenProject;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_CJ_NUMBER")
    public String getGivenCjNumber() {
        return givenCjNumber;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_CJ_NUMBER")
    public void setGivenCjNumber(String givenCjNumber) {
        this.givenCjNumber = givenCjNumber;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_PROJECT_ID")
    public Integer getGivenProjectId() {
        return givenProjectId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.GIVEN_PROJECT_ID")
    public void setGivenProjectId(Integer givenProjectId) {
        this.givenProjectId = givenProjectId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SORT_NUM")
    public Integer getSortNum() {
        return sortNum;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.SORT_NUM")
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CHANNEL_HOUSING_RESOURCES")
    public Integer getChannelHousingResources() {
        return channelHousingResources;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CHANNEL_HOUSING_RESOURCES")
    public void setChannelHousingResources(Integer channelHousingResources) {
        this.channelHousingResources = channelHousingResources;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CHANNEL_HAPPY_OFFICE")
    public Integer getChannelHappyOffice() {
        return channelHappyOffice;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.CHANNEL_HAPPY_OFFICE")
    public void setChannelHappyOffice(Integer channelHappyOffice) {
        this.channelHappyOffice = channelHappyOffice;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.EXCHANGE_CONDITION")
    public Integer getExchangeCondition() {
        return exchangeCondition;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.EXCHANGE_CONDITION")
    public void setExchangeCondition(Integer exchangeCondition) {
        this.exchangeCondition = exchangeCondition;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.EXCHANGE_THIRD_LINK")
    public String getExchangeThirdLink() {
        return exchangeThirdLink;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_COMMODITY.EXCHANGE_THIRD_LINK")
    public void setExchangeThirdLink(String exchangeThirdLink) {
        this.exchangeThirdLink = exchangeThirdLink;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_COMMODITY")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", shortName=").append(shortName);
        sb.append(", photoUrl=").append(photoUrl);
        sb.append(", count=").append(count);
        sb.append(", standard=").append(standard);
        sb.append(", modelNo=").append(modelNo);
        sb.append(", color=").append(color);
        sb.append(", size=").append(size);
        sb.append(", payMethod=").append(payMethod);
        sb.append(", auctionDate=").append(auctionDate);
        sb.append(", priceStart=").append(priceStart);
        sb.append(", priceJump=").append(priceJump);
        sb.append(", marketPrice=").append(marketPrice);
        sb.append(", price=").append(price);
        sb.append(", deliverDate=").append(deliverDate);
        sb.append(", deliverType=").append(deliverType);
        sb.append(", sellType=").append(sellType);
        sb.append(", status=").append(status);
        sb.append(", integral=").append(integral);
        sb.append(", isVerify=").append(isVerify);
        sb.append(", createDate=").append(createDate);
        sb.append(", auctionEndDate=").append(auctionEndDate);
        sb.append(", staffId=").append(staffId);
        sb.append(", staffName=").append(staffName);
        sb.append(", deptId=").append(deptId);
        sb.append(", deptName=").append(deptName);
        sb.append(", isDown=").append(isDown);
        sb.append(", isManualDown=").append(isManualDown);
        sb.append(", isCommission=").append(isCommission);
        sb.append(", commissionCmNo=").append(commissionCmNo);
        sb.append(", commissionCmName=").append(commissionCmName);
        sb.append(", contact=").append(contact);
        sb.append(", checkRemarks=").append(checkRemarks);
        sb.append(", priceMax=").append(priceMax);
        sb.append(", isWorkerPay=").append(isWorkerPay);
        sb.append(", sellerName=").append(sellerName);
        sb.append(", sellerWorkerId=").append(sellerWorkerId);
        sb.append(", sellerPhone=").append(sellerPhone);
        sb.append(", sellerQq=").append(sellerQq);
        sb.append(", givenChannel=").append(givenChannel);
        sb.append(", givenName=").append(givenName);
        sb.append(", givenWorkerId=").append(givenWorkerId);
        sb.append(", givenProject=").append(givenProject);
        sb.append(", givenCjNumber=").append(givenCjNumber);
        sb.append(", givenProjectId=").append(givenProjectId);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", channelHousingResources=").append(channelHousingResources);
        sb.append(", channelHappyOffice=").append(channelHappyOffice);
        sb.append(", exchangeCondition=").append(exchangeCondition);
        sb.append(", exchangeThirdLink=").append(exchangeThirdLink);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_COMMODITY")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JhsCommodity other = (JhsCommodity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getCategoryId() == null ? other.getCategoryId() == null : this.getCategoryId().equals(other.getCategoryId()))
            && (this.getShortName() == null ? other.getShortName() == null : this.getShortName().equals(other.getShortName()))
            && (this.getPhotoUrl() == null ? other.getPhotoUrl() == null : this.getPhotoUrl().equals(other.getPhotoUrl()))
            && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()))
            && (this.getStandard() == null ? other.getStandard() == null : this.getStandard().equals(other.getStandard()))
            && (this.getModelNo() == null ? other.getModelNo() == null : this.getModelNo().equals(other.getModelNo()))
            && (this.getColor() == null ? other.getColor() == null : this.getColor().equals(other.getColor()))
            && (this.getSize() == null ? other.getSize() == null : this.getSize().equals(other.getSize()))
            && (this.getPayMethod() == null ? other.getPayMethod() == null : this.getPayMethod().equals(other.getPayMethod()))
            && (this.getAuctionDate() == null ? other.getAuctionDate() == null : this.getAuctionDate().equals(other.getAuctionDate()))
            && (this.getPriceStart() == null ? other.getPriceStart() == null : this.getPriceStart().equals(other.getPriceStart()))
            && (this.getPriceJump() == null ? other.getPriceJump() == null : this.getPriceJump().equals(other.getPriceJump()))
            && (this.getMarketPrice() == null ? other.getMarketPrice() == null : this.getMarketPrice().equals(other.getMarketPrice()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getDeliverDate() == null ? other.getDeliverDate() == null : this.getDeliverDate().equals(other.getDeliverDate()))
            && (this.getDeliverType() == null ? other.getDeliverType() == null : this.getDeliverType().equals(other.getDeliverType()))
            && (this.getSellType() == null ? other.getSellType() == null : this.getSellType().equals(other.getSellType()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getIntegral() == null ? other.getIntegral() == null : this.getIntegral().equals(other.getIntegral()))
            && (this.getIsVerify() == null ? other.getIsVerify() == null : this.getIsVerify().equals(other.getIsVerify()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getAuctionEndDate() == null ? other.getAuctionEndDate() == null : this.getAuctionEndDate().equals(other.getAuctionEndDate()))
            && (this.getStaffId() == null ? other.getStaffId() == null : this.getStaffId().equals(other.getStaffId()))
            && (this.getStaffName() == null ? other.getStaffName() == null : this.getStaffName().equals(other.getStaffName()))
            && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
            && (this.getDeptName() == null ? other.getDeptName() == null : this.getDeptName().equals(other.getDeptName()))
            && (this.getIsDown() == null ? other.getIsDown() == null : this.getIsDown().equals(other.getIsDown()))
            && (this.getIsManualDown() == null ? other.getIsManualDown() == null : this.getIsManualDown().equals(other.getIsManualDown()))
            && (this.getIsCommission() == null ? other.getIsCommission() == null : this.getIsCommission().equals(other.getIsCommission()))
            && (this.getCommissionCmNo() == null ? other.getCommissionCmNo() == null : this.getCommissionCmNo().equals(other.getCommissionCmNo()))
            && (this.getCommissionCmName() == null ? other.getCommissionCmName() == null : this.getCommissionCmName().equals(other.getCommissionCmName()))
            && (this.getContact() == null ? other.getContact() == null : this.getContact().equals(other.getContact()))
            && (this.getCheckRemarks() == null ? other.getCheckRemarks() == null : this.getCheckRemarks().equals(other.getCheckRemarks()))
            && (this.getPriceMax() == null ? other.getPriceMax() == null : this.getPriceMax().equals(other.getPriceMax()))
            && (this.getIsWorkerPay() == null ? other.getIsWorkerPay() == null : this.getIsWorkerPay().equals(other.getIsWorkerPay()))
            && (this.getSellerName() == null ? other.getSellerName() == null : this.getSellerName().equals(other.getSellerName()))
            && (this.getSellerWorkerId() == null ? other.getSellerWorkerId() == null : this.getSellerWorkerId().equals(other.getSellerWorkerId()))
            && (this.getSellerPhone() == null ? other.getSellerPhone() == null : this.getSellerPhone().equals(other.getSellerPhone()))
            && (this.getSellerQq() == null ? other.getSellerQq() == null : this.getSellerQq().equals(other.getSellerQq()))
            && (this.getGivenChannel() == null ? other.getGivenChannel() == null : this.getGivenChannel().equals(other.getGivenChannel()))
            && (this.getGivenName() == null ? other.getGivenName() == null : this.getGivenName().equals(other.getGivenName()))
            && (this.getGivenWorkerId() == null ? other.getGivenWorkerId() == null : this.getGivenWorkerId().equals(other.getGivenWorkerId()))
            && (this.getGivenProject() == null ? other.getGivenProject() == null : this.getGivenProject().equals(other.getGivenProject()))
            && (this.getGivenCjNumber() == null ? other.getGivenCjNumber() == null : this.getGivenCjNumber().equals(other.getGivenCjNumber()))
            && (this.getGivenProjectId() == null ? other.getGivenProjectId() == null : this.getGivenProjectId().equals(other.getGivenProjectId()))
            && (this.getSortNum() == null ? other.getSortNum() == null : this.getSortNum().equals(other.getSortNum()))
            && (this.getChannelHousingResources() == null ? other.getChannelHousingResources() == null : this.getChannelHousingResources().equals(other.getChannelHousingResources()))
            && (this.getChannelHappyOffice() == null ? other.getChannelHappyOffice() == null : this.getChannelHappyOffice().equals(other.getChannelHappyOffice()))
            && (this.getExchangeCondition() == null ? other.getExchangeCondition() == null : this.getExchangeCondition().equals(other.getExchangeCondition()))
            && (this.getExchangeThirdLink() == null ? other.getExchangeThirdLink() == null : this.getExchangeThirdLink().equals(other.getExchangeThirdLink()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_COMMODITY")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getCategoryId() == null) ? 0 : getCategoryId().hashCode());
        result = prime * result + ((getShortName() == null) ? 0 : getShortName().hashCode());
        result = prime * result + ((getPhotoUrl() == null) ? 0 : getPhotoUrl().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        result = prime * result + ((getStandard() == null) ? 0 : getStandard().hashCode());
        result = prime * result + ((getModelNo() == null) ? 0 : getModelNo().hashCode());
        result = prime * result + ((getColor() == null) ? 0 : getColor().hashCode());
        result = prime * result + ((getSize() == null) ? 0 : getSize().hashCode());
        result = prime * result + ((getPayMethod() == null) ? 0 : getPayMethod().hashCode());
        result = prime * result + ((getAuctionDate() == null) ? 0 : getAuctionDate().hashCode());
        result = prime * result + ((getPriceStart() == null) ? 0 : getPriceStart().hashCode());
        result = prime * result + ((getPriceJump() == null) ? 0 : getPriceJump().hashCode());
        result = prime * result + ((getMarketPrice() == null) ? 0 : getMarketPrice().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getDeliverDate() == null) ? 0 : getDeliverDate().hashCode());
        result = prime * result + ((getDeliverType() == null) ? 0 : getDeliverType().hashCode());
        result = prime * result + ((getSellType() == null) ? 0 : getSellType().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getIntegral() == null) ? 0 : getIntegral().hashCode());
        result = prime * result + ((getIsVerify() == null) ? 0 : getIsVerify().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getAuctionEndDate() == null) ? 0 : getAuctionEndDate().hashCode());
        result = prime * result + ((getStaffId() == null) ? 0 : getStaffId().hashCode());
        result = prime * result + ((getStaffName() == null) ? 0 : getStaffName().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        result = prime * result + ((getDeptName() == null) ? 0 : getDeptName().hashCode());
        result = prime * result + ((getIsDown() == null) ? 0 : getIsDown().hashCode());
        result = prime * result + ((getIsManualDown() == null) ? 0 : getIsManualDown().hashCode());
        result = prime * result + ((getIsCommission() == null) ? 0 : getIsCommission().hashCode());
        result = prime * result + ((getCommissionCmNo() == null) ? 0 : getCommissionCmNo().hashCode());
        result = prime * result + ((getCommissionCmName() == null) ? 0 : getCommissionCmName().hashCode());
        result = prime * result + ((getContact() == null) ? 0 : getContact().hashCode());
        result = prime * result + ((getCheckRemarks() == null) ? 0 : getCheckRemarks().hashCode());
        result = prime * result + ((getPriceMax() == null) ? 0 : getPriceMax().hashCode());
        result = prime * result + ((getIsWorkerPay() == null) ? 0 : getIsWorkerPay().hashCode());
        result = prime * result + ((getSellerName() == null) ? 0 : getSellerName().hashCode());
        result = prime * result + ((getSellerWorkerId() == null) ? 0 : getSellerWorkerId().hashCode());
        result = prime * result + ((getSellerPhone() == null) ? 0 : getSellerPhone().hashCode());
        result = prime * result + ((getSellerQq() == null) ? 0 : getSellerQq().hashCode());
        result = prime * result + ((getGivenChannel() == null) ? 0 : getGivenChannel().hashCode());
        result = prime * result + ((getGivenName() == null) ? 0 : getGivenName().hashCode());
        result = prime * result + ((getGivenWorkerId() == null) ? 0 : getGivenWorkerId().hashCode());
        result = prime * result + ((getGivenProject() == null) ? 0 : getGivenProject().hashCode());
        result = prime * result + ((getGivenCjNumber() == null) ? 0 : getGivenCjNumber().hashCode());
        result = prime * result + ((getGivenProjectId() == null) ? 0 : getGivenProjectId().hashCode());
        result = prime * result + ((getSortNum() == null) ? 0 : getSortNum().hashCode());
        result = prime * result + ((getChannelHousingResources() == null) ? 0 : getChannelHousingResources().hashCode());
        result = prime * result + ((getChannelHappyOffice() == null) ? 0 : getChannelHappyOffice().hashCode());
        result = prime * result + ((getExchangeCondition() == null) ? 0 : getExchangeCondition().hashCode());
        result = prime * result + ((getExchangeThirdLink() == null) ? 0 : getExchangeThirdLink().hashCode());
        return result;
    }
}