package com.leyoujia.coa.zc.mall.dao.erp.entity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table JHS_EXCHANGE_SIZE
 */
public class JhsExchangeSize implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.ID")
    private Integer id;

    /**
     * Database Column Remarks:
     *   订单类型 1为普通订单 2为子订单
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.ORDER_TYPE")
    private Integer orderType;

    /**
     * Database Column Remarks:
     *   订单ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.ORDER_ID")
    private Integer orderId;

    /**
     * Database Column Remarks:
     *   商品ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.COMMODITY_ID")
    private Integer commodityId;

    /**
     * Database Column Remarks:
     *   商品名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.COMMODITY_NAME")
    private String commodityName;

    /**
     * Database Column Remarks:
     *   旧尺码
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.OLD_SIZE")
    private String oldSize;

    /**
     * Database Column Remarks:
     *   新尺码
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.NEW_SIZE")
    private String newSize;

    /**
     * Database Column Remarks:
     *   置换数量
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.COUNT")
    private Integer count;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.CREATE_DATE")
    private Date createDate;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.UPDATE_DATE")
    private Date updateDate;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_EXCHANGE_SIZE")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.ORDER_TYPE")
    public Integer getOrderType() {
        return orderType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.ORDER_TYPE")
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.ORDER_ID")
    public Integer getOrderId() {
        return orderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.ORDER_ID")
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.COMMODITY_ID")
    public Integer getCommodityId() {
        return commodityId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.COMMODITY_ID")
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.COMMODITY_NAME")
    public String getCommodityName() {
        return commodityName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.COMMODITY_NAME")
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.OLD_SIZE")
    public String getOldSize() {
        return oldSize;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.OLD_SIZE")
    public void setOldSize(String oldSize) {
        this.oldSize = oldSize;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.NEW_SIZE")
    public String getNewSize() {
        return newSize;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.NEW_SIZE")
    public void setNewSize(String newSize) {
        this.newSize = newSize;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.COUNT")
    public Integer getCount() {
        return count;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.COUNT")
    public void setCount(Integer count) {
        this.count = count;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.CREATE_DATE")
    public Date getCreateDate() {
        return createDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.CREATE_DATE")
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.UPDATE_DATE")
    public Date getUpdateDate() {
        return updateDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_EXCHANGE_SIZE.UPDATE_DATE")
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_EXCHANGE_SIZE")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderType=").append(orderType);
        sb.append(", orderId=").append(orderId);
        sb.append(", commodityId=").append(commodityId);
        sb.append(", commodityName=").append(commodityName);
        sb.append(", oldSize=").append(oldSize);
        sb.append(", newSize=").append(newSize);
        sb.append(", count=").append(count);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_EXCHANGE_SIZE")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JhsExchangeSize other = (JhsExchangeSize) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderType() == null ? other.getOrderType() == null : this.getOrderType().equals(other.getOrderType()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getCommodityId() == null ? other.getCommodityId() == null : this.getCommodityId().equals(other.getCommodityId()))
            && (this.getCommodityName() == null ? other.getCommodityName() == null : this.getCommodityName().equals(other.getCommodityName()))
            && (this.getOldSize() == null ? other.getOldSize() == null : this.getOldSize().equals(other.getOldSize()))
            && (this.getNewSize() == null ? other.getNewSize() == null : this.getNewSize().equals(other.getNewSize()))
            && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_EXCHANGE_SIZE")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderType() == null) ? 0 : getOrderType().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getCommodityId() == null) ? 0 : getCommodityId().hashCode());
        result = prime * result + ((getCommodityName() == null) ? 0 : getCommodityName().hashCode());
        result = prime * result + ((getOldSize() == null) ? 0 : getOldSize().hashCode());
        result = prime * result + ((getNewSize() == null) ? 0 : getNewSize().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}