package com.leyoujia.coa.zc.mall.dao.erp.entity;

import java.io.Serializable;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   体检人信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table JHS_MEDICAL_EXAMINER
 */
public class JhsMedicalExaminer implements Serializable {
    /**
     * Database Column Remarks:
     *   自增主键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.id")
    private Integer id;

    /**
     * Database Column Remarks:
     *   订单id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.order_id")
    private Integer orderId;

    /**
     * Database Column Remarks:
     *   体检人姓名
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.examiner_name")
    private String examinerName;

    /**
     * Database Column Remarks:
     *   体检人身份证号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.examiner_IDCard")
    private String examinerIdcard;

    /**
     * Database Column Remarks:
     *   电话号码
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.phone_number")
    private String phoneNumber;

    /**
     * Database Column Remarks:
     *   省份编号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.province_code")
    private String provinceCode;

    /**
     * Database Column Remarks:
     *   省份名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.province_name")
    private String provinceName;

    /**
     * Database Column Remarks:
     *   城市编号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.city_code")
    private String cityCode;

    /**
     * Database Column Remarks:
     *   城市名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.city_name")
    private String cityName;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_MEDICAL_EXAMINER")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.order_id")
    public Integer getOrderId() {
        return orderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.order_id")
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.examiner_name")
    public String getExaminerName() {
        return examinerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.examiner_name")
    public void setExaminerName(String examinerName) {
        this.examinerName = examinerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.examiner_IDCard")
    public String getExaminerIdcard() {
        return examinerIdcard;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.examiner_IDCard")
    public void setExaminerIdcard(String examinerIdcard) {
        this.examinerIdcard = examinerIdcard;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.phone_number")
    public String getPhoneNumber() {
        return phoneNumber;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.phone_number")
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.province_code")
    public String getProvinceCode() {
        return provinceCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.province_code")
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.province_name")
    public String getProvinceName() {
        return provinceName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.province_name")
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.city_code")
    public String getCityCode() {
        return cityCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.city_code")
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.city_name")
    public String getCityName() {
        return cityName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_MEDICAL_EXAMINER.city_name")
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_MEDICAL_EXAMINER")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", examinerName=").append(examinerName);
        sb.append(", examinerIdcard=").append(examinerIdcard);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", provinceCode=").append(provinceCode);
        sb.append(", provinceName=").append(provinceName);
        sb.append(", cityCode=").append(cityCode);
        sb.append(", cityName=").append(cityName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_MEDICAL_EXAMINER")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JhsMedicalExaminer other = (JhsMedicalExaminer) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getExaminerName() == null ? other.getExaminerName() == null : this.getExaminerName().equals(other.getExaminerName()))
            && (this.getExaminerIdcard() == null ? other.getExaminerIdcard() == null : this.getExaminerIdcard().equals(other.getExaminerIdcard()))
            && (this.getPhoneNumber() == null ? other.getPhoneNumber() == null : this.getPhoneNumber().equals(other.getPhoneNumber()))
            && (this.getProvinceCode() == null ? other.getProvinceCode() == null : this.getProvinceCode().equals(other.getProvinceCode()))
            && (this.getProvinceName() == null ? other.getProvinceName() == null : this.getProvinceName().equals(other.getProvinceName()))
            && (this.getCityCode() == null ? other.getCityCode() == null : this.getCityCode().equals(other.getCityCode()))
            && (this.getCityName() == null ? other.getCityName() == null : this.getCityName().equals(other.getCityName()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_MEDICAL_EXAMINER")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getExaminerName() == null) ? 0 : getExaminerName().hashCode());
        result = prime * result + ((getExaminerIdcard() == null) ? 0 : getExaminerIdcard().hashCode());
        result = prime * result + ((getPhoneNumber() == null) ? 0 : getPhoneNumber().hashCode());
        result = prime * result + ((getProvinceCode() == null) ? 0 : getProvinceCode().hashCode());
        result = prime * result + ((getProvinceName() == null) ? 0 : getProvinceName().hashCode());
        result = prime * result + ((getCityCode() == null) ? 0 : getCityCode().hashCode());
        result = prime * result + ((getCityName() == null) ? 0 : getCityName().hashCode());
        return result;
    }
}