package com.leyoujia.coa.zc.mall.dao.erp.entity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   商城操作日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table JHS_OPERATION_LOG
 */
public class JhsOperationLog implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.ID")
    private Integer id;

    /**
     * Database Column Remarks:
     *   业务类型 1 商城订单
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.BUS_TYPE")
    private Integer busType;

    /**
     * Database Column Remarks:
     *   业务id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.BUS_ID")
    private Integer busId;

    /**
     * Database Column Remarks:
     *   操作类型
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.OP_TYPE")
    private String opType;

    /**
     * Database Column Remarks:
     *   操作内容
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.OP_CONTENT")
    private String opContent;

    /**
     * Database Column Remarks:
     *   操作人id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.OP_WORKER_ID")
    private String opWorkerId;

    /**
     * Database Column Remarks:
     *   操作人名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.OP_WORKER_NAME")
    private String opWorkerName;

    /**
     * Database Column Remarks:
     *   状态 0 无效 1 有效
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.STATUS")
    private Integer status;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.CREATE_TIME")
    private Date createTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.EXTRA1")
    private String extra1;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.EXTRA2")
    private String extra2;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_OPERATION_LOG")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.BUS_TYPE")
    public Integer getBusType() {
        return busType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.BUS_TYPE")
    public void setBusType(Integer busType) {
        this.busType = busType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.BUS_ID")
    public Integer getBusId() {
        return busId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.BUS_ID")
    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.OP_TYPE")
    public String getOpType() {
        return opType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.OP_TYPE")
    public void setOpType(String opType) {
        this.opType = opType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.OP_CONTENT")
    public String getOpContent() {
        return opContent;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.OP_CONTENT")
    public void setOpContent(String opContent) {
        this.opContent = opContent;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.OP_WORKER_ID")
    public String getOpWorkerId() {
        return opWorkerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.OP_WORKER_ID")
    public void setOpWorkerId(String opWorkerId) {
        this.opWorkerId = opWorkerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.OP_WORKER_NAME")
    public String getOpWorkerName() {
        return opWorkerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.OP_WORKER_NAME")
    public void setOpWorkerName(String opWorkerName) {
        this.opWorkerName = opWorkerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.STATUS")
    public Integer getStatus() {
        return status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.STATUS")
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.CREATE_TIME")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.CREATE_TIME")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.EXTRA1")
    public String getExtra1() {
        return extra1;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.EXTRA1")
    public void setExtra1(String extra1) {
        this.extra1 = extra1;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.EXTRA2")
    public String getExtra2() {
        return extra2;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_OPERATION_LOG.EXTRA2")
    public void setExtra2(String extra2) {
        this.extra2 = extra2;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_OPERATION_LOG")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", busType=").append(busType);
        sb.append(", busId=").append(busId);
        sb.append(", opType=").append(opType);
        sb.append(", opContent=").append(opContent);
        sb.append(", opWorkerId=").append(opWorkerId);
        sb.append(", opWorkerName=").append(opWorkerName);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", extra1=").append(extra1);
        sb.append(", extra2=").append(extra2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_OPERATION_LOG")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JhsOperationLog other = (JhsOperationLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBusType() == null ? other.getBusType() == null : this.getBusType().equals(other.getBusType()))
            && (this.getBusId() == null ? other.getBusId() == null : this.getBusId().equals(other.getBusId()))
            && (this.getOpType() == null ? other.getOpType() == null : this.getOpType().equals(other.getOpType()))
            && (this.getOpContent() == null ? other.getOpContent() == null : this.getOpContent().equals(other.getOpContent()))
            && (this.getOpWorkerId() == null ? other.getOpWorkerId() == null : this.getOpWorkerId().equals(other.getOpWorkerId()))
            && (this.getOpWorkerName() == null ? other.getOpWorkerName() == null : this.getOpWorkerName().equals(other.getOpWorkerName()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getExtra1() == null ? other.getExtra1() == null : this.getExtra1().equals(other.getExtra1()))
            && (this.getExtra2() == null ? other.getExtra2() == null : this.getExtra2().equals(other.getExtra2()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_OPERATION_LOG")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBusType() == null) ? 0 : getBusType().hashCode());
        result = prime * result + ((getBusId() == null) ? 0 : getBusId().hashCode());
        result = prime * result + ((getOpType() == null) ? 0 : getOpType().hashCode());
        result = prime * result + ((getOpContent() == null) ? 0 : getOpContent().hashCode());
        result = prime * result + ((getOpWorkerId() == null) ? 0 : getOpWorkerId().hashCode());
        result = prime * result + ((getOpWorkerName() == null) ? 0 : getOpWorkerName().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getExtra1() == null) ? 0 : getExtra1().hashCode());
        result = prime * result + ((getExtra2() == null) ? 0 : getExtra2().hashCode());
        return result;
    }
}