package com.leyoujia.coa.zc.mall.dao.erp.entity;

import java.io.Serializable;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table JHS_SUBJECT
 */
public class JhsSubject implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.ID")
    private Integer id;

    /**
     * Database Column Remarks:
     *   类别名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_NAME")
    private String subName;

    /**
     * Database Column Remarks:
     *   类别父ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_PARENTID")
    private Integer subParentid;

    /**
     * Database Column Remarks:
     *   类别根ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_ROOTID")
    private Integer subRootid;

    /**
     * Database Column Remarks:
     *   关联树状
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_PATH")
    private String subPath;

    /**
     * Database Column Remarks:
     *   简写
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_SPELL")
    private String subSpell;

    /**
     * Database Column Remarks:
     *   深度
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_DEPTH")
    private Byte subDepth;

    /**
     * Database Column Remarks:
     *   子节点个数
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_LEAF_NUM")
    private Byte subLeafNum;

    /**
     * Database Column Remarks:
     *   排序
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_ORDERING")
    private Integer subOrdering;

    /**
     * Database Column Remarks:
     *   状态
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_STATE")
    private String subState;

    /**
     * Database Column Remarks:
     *   对应的供应商ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUPPLIER_ID")
    private Integer supplierId;

    /**
     * Database Column Remarks:
     *   供应商联系人
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUPPLIER_CONTACT")
    private String supplierContact;

    /**
     * Database Column Remarks:
     *   供应商名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUPPLIER_NAME")
    private String supplierName;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_SUBJECT")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_NAME")
    public String getSubName() {
        return subName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_NAME")
    public void setSubName(String subName) {
        this.subName = subName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_PARENTID")
    public Integer getSubParentid() {
        return subParentid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_PARENTID")
    public void setSubParentid(Integer subParentid) {
        this.subParentid = subParentid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_ROOTID")
    public Integer getSubRootid() {
        return subRootid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_ROOTID")
    public void setSubRootid(Integer subRootid) {
        this.subRootid = subRootid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_PATH")
    public String getSubPath() {
        return subPath;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_PATH")
    public void setSubPath(String subPath) {
        this.subPath = subPath;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_SPELL")
    public String getSubSpell() {
        return subSpell;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_SPELL")
    public void setSubSpell(String subSpell) {
        this.subSpell = subSpell;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_DEPTH")
    public Byte getSubDepth() {
        return subDepth;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_DEPTH")
    public void setSubDepth(Byte subDepth) {
        this.subDepth = subDepth;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_LEAF_NUM")
    public Byte getSubLeafNum() {
        return subLeafNum;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_LEAF_NUM")
    public void setSubLeafNum(Byte subLeafNum) {
        this.subLeafNum = subLeafNum;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_ORDERING")
    public Integer getSubOrdering() {
        return subOrdering;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_ORDERING")
    public void setSubOrdering(Integer subOrdering) {
        this.subOrdering = subOrdering;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_STATE")
    public String getSubState() {
        return subState;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUB_STATE")
    public void setSubState(String subState) {
        this.subState = subState;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUPPLIER_ID")
    public Integer getSupplierId() {
        return supplierId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUPPLIER_ID")
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUPPLIER_CONTACT")
    public String getSupplierContact() {
        return supplierContact;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUPPLIER_CONTACT")
    public void setSupplierContact(String supplierContact) {
        this.supplierContact = supplierContact;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUPPLIER_NAME")
    public String getSupplierName() {
        return supplierName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_SUBJECT.SUPPLIER_NAME")
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_SUBJECT")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", subName=").append(subName);
        sb.append(", subParentid=").append(subParentid);
        sb.append(", subRootid=").append(subRootid);
        sb.append(", subPath=").append(subPath);
        sb.append(", subSpell=").append(subSpell);
        sb.append(", subDepth=").append(subDepth);
        sb.append(", subLeafNum=").append(subLeafNum);
        sb.append(", subOrdering=").append(subOrdering);
        sb.append(", subState=").append(subState);
        sb.append(", supplierId=").append(supplierId);
        sb.append(", supplierContact=").append(supplierContact);
        sb.append(", supplierName=").append(supplierName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_SUBJECT")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JhsSubject other = (JhsSubject) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSubName() == null ? other.getSubName() == null : this.getSubName().equals(other.getSubName()))
            && (this.getSubParentid() == null ? other.getSubParentid() == null : this.getSubParentid().equals(other.getSubParentid()))
            && (this.getSubRootid() == null ? other.getSubRootid() == null : this.getSubRootid().equals(other.getSubRootid()))
            && (this.getSubPath() == null ? other.getSubPath() == null : this.getSubPath().equals(other.getSubPath()))
            && (this.getSubSpell() == null ? other.getSubSpell() == null : this.getSubSpell().equals(other.getSubSpell()))
            && (this.getSubDepth() == null ? other.getSubDepth() == null : this.getSubDepth().equals(other.getSubDepth()))
            && (this.getSubLeafNum() == null ? other.getSubLeafNum() == null : this.getSubLeafNum().equals(other.getSubLeafNum()))
            && (this.getSubOrdering() == null ? other.getSubOrdering() == null : this.getSubOrdering().equals(other.getSubOrdering()))
            && (this.getSubState() == null ? other.getSubState() == null : this.getSubState().equals(other.getSubState()))
            && (this.getSupplierId() == null ? other.getSupplierId() == null : this.getSupplierId().equals(other.getSupplierId()))
            && (this.getSupplierContact() == null ? other.getSupplierContact() == null : this.getSupplierContact().equals(other.getSupplierContact()))
            && (this.getSupplierName() == null ? other.getSupplierName() == null : this.getSupplierName().equals(other.getSupplierName()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_SUBJECT")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSubName() == null) ? 0 : getSubName().hashCode());
        result = prime * result + ((getSubParentid() == null) ? 0 : getSubParentid().hashCode());
        result = prime * result + ((getSubRootid() == null) ? 0 : getSubRootid().hashCode());
        result = prime * result + ((getSubPath() == null) ? 0 : getSubPath().hashCode());
        result = prime * result + ((getSubSpell() == null) ? 0 : getSubSpell().hashCode());
        result = prime * result + ((getSubDepth() == null) ? 0 : getSubDepth().hashCode());
        result = prime * result + ((getSubLeafNum() == null) ? 0 : getSubLeafNum().hashCode());
        result = prime * result + ((getSubOrdering() == null) ? 0 : getSubOrdering().hashCode());
        result = prime * result + ((getSubState() == null) ? 0 : getSubState().hashCode());
        result = prime * result + ((getSupplierId() == null) ? 0 : getSupplierId().hashCode());
        result = prime * result + ((getSupplierContact() == null) ? 0 : getSupplierContact().hashCode());
        result = prime * result + ((getSupplierName() == null) ? 0 : getSupplierName().hashCode());
        return result;
    }
}