package com.leyoujia.coa.zc.mall.dao.erp.entity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   交易订单表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table JHS_TRADE_ORDER
 */
public class JhsTradeOrder implements Serializable {
    /**
     * Database Column Remarks:
     *   主键ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.ID")
    private Integer id;

    /**
     * Database Column Remarks:
     *   订单号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.ORDER_NO")
    private String orderNo;

    /**
     * Database Column Remarks:
     *   类型[1一般交易,2拍卖,3工资代扣,4公费,5离职代扣]
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.TYPE")
    private Integer type;

    /**
     * Database Column Remarks:
     *   商品ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.COMMODITY_ID")
    private Integer commodityId;

    /**
     * Database Column Remarks:
     *   商品名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.COMMODITY_NAME")
    private String commodityName;

    /**
     * Database Column Remarks:
     *   单价
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PRICE")
    private Double price;

    /**
     * Database Column Remarks:
     *   数量
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.COUNT")
    private Integer count;

    /**
     * Database Column Remarks:
     *   总价
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.TOTAL")
    private Double total;

    /**
     * Database Column Remarks:
     *   来源 1 pc乐划算 2 乐办公 3 乐有家网
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.OFROM")
    private Integer ofrom;

    /**
     * Database Column Remarks:
     *    -1已过期, 0等待付款, 1已取消, 2已付款, 3已发货, 4买家已收货, 5交易成功, 8已结款, 11待确认收款,  99交易关闭, 20工资代扣, 21公费, 30退款审批中、31退款审批不通过、32退款审批通过、33已退款、40报销审批中、41报销审批不通过、42报销审批通过
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.STATUS")
    private Integer status;

    /**
     * Database Column Remarks:
     *   员工ID/用户标识
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.WORKER_ID")
    private String workerId;

    /**
     * Database Column Remarks:
     *   员工名字
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.WORKER_NAME")
    private String workerName;

    /**
     * Database Column Remarks:
     *   创建日期
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.CREATE_DATE")
    private Date createDate;

    /**
     * Database Column Remarks:
     *   卖家ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SELLER_ID")
    private String sellerId;

    /**
     * Database Column Remarks:
     *   卖家名字
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SELLER_NAME")
    private String sellerName;

    /**
     * Database Column Remarks:
     *   卖家部门id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SELLER_DEPT_ID")
    private String sellerDeptId;

    /**
     * Database Column Remarks:
     *   卖家部门name
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SELLER_DEPT_NAME")
    private String sellerDeptName;

    /**
     * Database Column Remarks:
     *   消费者部门id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BUYER_DEPT_ID")
    private String buyerDeptId;

    /**
     * Database Column Remarks:
     *   消费者部门name
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BUYER_DEPT_NAME")
    private String buyerDeptName;

    /**
     * Database Column Remarks:
     *   积分
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.INTEGRAL")
    private Integer integral;

    /**
     * Database Column Remarks:
     *    规格
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.STANDARD")
    private String standard;

    /**
     * Database Column Remarks:
     *   收件人
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.RECIPIENTS")
    private String recipients;

    /**
     * Database Column Remarks:
     *   买家联系方式
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BUYER_TEL")
    private String buyerTel;

    /**
     * Database Column Remarks:
     *   买家联系地址
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BUYER_ADDRESS")
    private String buyerAddress;

    /**
     * Database Column Remarks:
     *   备注说明
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.REMARKS")
    private String remarks;

    /**
     * Database Column Remarks:
     *   省
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PROVINCE")
    private String province;

    /**
     * Database Column Remarks:
     *   市
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.CITY")
    private String city;

    /**
     * Database Column Remarks:
     *   区
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.AREA")
    private String area;

    /**
     * Database Column Remarks:
     *   分行名/地址
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SHOP_ADDR")
    private String shopAddr;

    /**
     * Database Column Remarks:
     *   快递公司
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.POST_COMPANY")
    private String postCompany;

    /**
     * Database Column Remarks:
     *   快递单号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.POST_NO")
    private String postNo;

    /**
     * Database Column Remarks:
     *   付款时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PAY_DATE")
    private Date payDate;

    /**
     * Database Column Remarks:
     *   发货时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.DELIVER_DATE")
    private Date deliverDate;

    /**
     * Database Column Remarks:
     *   发货信息
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.DELIVER_MSG")
    private String deliverMsg;

    /**
     * Database Column Remarks:
     *   确认收货时间/交易成功时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.RECEIPT_DATE")
    private Date receiptDate;

    /**
     * Database Column Remarks:
     *   收货方式：1快递，2自取
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.TAKE_TYPE")
    private Integer takeType;

    /**
     * Database Column Remarks:
     *   是否产生快乐基金记录 1是
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.IS_CREATE_HAPPY")
    private String isCreateHappy;

    /**
     * Database Column Remarks:
     *   支付方式(0现金1现金和积分 废除)2支付宝3储备奖4顺豆
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PAY_METHOD")
    private String payMethod;

    /**
     * Database Column Remarks:
     *   所属分类
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.DICTTEXT")
    private String dicttext;

    /**
     * Database Column Remarks:
     *   结款单打印时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PRINT_DATE")
    private Date printDate;

    /**
     * Database Column Remarks:
     *   结款时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PAYMENT_DATE")
    private Date paymentDate;

    /**
     * Database Column Remarks:
     *   交易终止时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.STOP_TRADE_DATE")
    private Date stopTradeDate;

    /**
     * Database Column Remarks:
     *   数据版本 版本1 无供应商管理的订单数据(包含历史数据) 版本2添加了诸多订单明细字段,由资产作为供应商管理服装类数据 版本3 由外部供应商管理服装类数据
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.DATA_VERSION")
    private Integer dataVersion;

    /**
     * Database Column Remarks:
     *   订单对应报销单id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.REIMBURSEMENT_ID")
    private Integer reimbursementId;

    /**
     * Database Column Remarks:
     *   退款原因
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.REFUND_REASON")
    private String refundReason;

    /**
     * Database Column Remarks:
     *   退款报销单id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.REFUND_REIMBURSEMENT_ID")
    private Integer refundReimbursementId;

    /**
     * Database Column Remarks:
     *   兑换方式 1 兑换码 2 兑换链接
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.EXCHANGE_METHOD")
    private Integer exchangeMethod;

    /**
     * Database Column Remarks:
     *   兑换链接
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.EXCHANGE_LINK")
    private String exchangeLink;

    /**
     * Database Column Remarks:
     *   兑换码
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.EXCHANGE_CODE")
    private String exchangeCode;

    /**
     * Database Column Remarks:
     *   时间戳标识
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BI_DATE")
    private Date biDate;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_TRADE_ORDER")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.ORDER_NO")
    public String getOrderNo() {
        return orderNo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.ORDER_NO")
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.TYPE")
    public Integer getType() {
        return type;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.TYPE")
    public void setType(Integer type) {
        this.type = type;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.COMMODITY_ID")
    public Integer getCommodityId() {
        return commodityId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.COMMODITY_ID")
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.COMMODITY_NAME")
    public String getCommodityName() {
        return commodityName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.COMMODITY_NAME")
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PRICE")
    public Double getPrice() {
        return price;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PRICE")
    public void setPrice(Double price) {
        this.price = price;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.COUNT")
    public Integer getCount() {
        return count;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.COUNT")
    public void setCount(Integer count) {
        this.count = count;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.TOTAL")
    public Double getTotal() {
        return total;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.TOTAL")
    public void setTotal(Double total) {
        this.total = total;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.OFROM")
    public Integer getOfrom() {
        return ofrom;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.OFROM")
    public void setOfrom(Integer ofrom) {
        this.ofrom = ofrom;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.STATUS")
    public Integer getStatus() {
        return status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.STATUS")
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.WORKER_ID")
    public String getWorkerId() {
        return workerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.WORKER_ID")
    public void setWorkerId(String workerId) {
        this.workerId = workerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.WORKER_NAME")
    public String getWorkerName() {
        return workerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.WORKER_NAME")
    public void setWorkerName(String workerName) {
        this.workerName = workerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.CREATE_DATE")
    public Date getCreateDate() {
        return createDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.CREATE_DATE")
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SELLER_ID")
    public String getSellerId() {
        return sellerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SELLER_ID")
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SELLER_NAME")
    public String getSellerName() {
        return sellerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SELLER_NAME")
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SELLER_DEPT_ID")
    public String getSellerDeptId() {
        return sellerDeptId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SELLER_DEPT_ID")
    public void setSellerDeptId(String sellerDeptId) {
        this.sellerDeptId = sellerDeptId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SELLER_DEPT_NAME")
    public String getSellerDeptName() {
        return sellerDeptName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SELLER_DEPT_NAME")
    public void setSellerDeptName(String sellerDeptName) {
        this.sellerDeptName = sellerDeptName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BUYER_DEPT_ID")
    public String getBuyerDeptId() {
        return buyerDeptId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BUYER_DEPT_ID")
    public void setBuyerDeptId(String buyerDeptId) {
        this.buyerDeptId = buyerDeptId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BUYER_DEPT_NAME")
    public String getBuyerDeptName() {
        return buyerDeptName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BUYER_DEPT_NAME")
    public void setBuyerDeptName(String buyerDeptName) {
        this.buyerDeptName = buyerDeptName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.INTEGRAL")
    public Integer getIntegral() {
        return integral;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.INTEGRAL")
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.STANDARD")
    public String getStandard() {
        return standard;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.STANDARD")
    public void setStandard(String standard) {
        this.standard = standard;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.RECIPIENTS")
    public String getRecipients() {
        return recipients;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.RECIPIENTS")
    public void setRecipients(String recipients) {
        this.recipients = recipients;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BUYER_TEL")
    public String getBuyerTel() {
        return buyerTel;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BUYER_TEL")
    public void setBuyerTel(String buyerTel) {
        this.buyerTel = buyerTel;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BUYER_ADDRESS")
    public String getBuyerAddress() {
        return buyerAddress;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BUYER_ADDRESS")
    public void setBuyerAddress(String buyerAddress) {
        this.buyerAddress = buyerAddress;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.REMARKS")
    public String getRemarks() {
        return remarks;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.REMARKS")
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PROVINCE")
    public String getProvince() {
        return province;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PROVINCE")
    public void setProvince(String province) {
        this.province = province;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.CITY")
    public String getCity() {
        return city;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.CITY")
    public void setCity(String city) {
        this.city = city;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.AREA")
    public String getArea() {
        return area;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.AREA")
    public void setArea(String area) {
        this.area = area;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SHOP_ADDR")
    public String getShopAddr() {
        return shopAddr;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.SHOP_ADDR")
    public void setShopAddr(String shopAddr) {
        this.shopAddr = shopAddr;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.POST_COMPANY")
    public String getPostCompany() {
        return postCompany;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.POST_COMPANY")
    public void setPostCompany(String postCompany) {
        this.postCompany = postCompany;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.POST_NO")
    public String getPostNo() {
        return postNo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.POST_NO")
    public void setPostNo(String postNo) {
        this.postNo = postNo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PAY_DATE")
    public Date getPayDate() {
        return payDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PAY_DATE")
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.DELIVER_DATE")
    public Date getDeliverDate() {
        return deliverDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.DELIVER_DATE")
    public void setDeliverDate(Date deliverDate) {
        this.deliverDate = deliverDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.DELIVER_MSG")
    public String getDeliverMsg() {
        return deliverMsg;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.DELIVER_MSG")
    public void setDeliverMsg(String deliverMsg) {
        this.deliverMsg = deliverMsg;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.RECEIPT_DATE")
    public Date getReceiptDate() {
        return receiptDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.RECEIPT_DATE")
    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.TAKE_TYPE")
    public Integer getTakeType() {
        return takeType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.TAKE_TYPE")
    public void setTakeType(Integer takeType) {
        this.takeType = takeType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.IS_CREATE_HAPPY")
    public String getIsCreateHappy() {
        return isCreateHappy;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.IS_CREATE_HAPPY")
    public void setIsCreateHappy(String isCreateHappy) {
        this.isCreateHappy = isCreateHappy;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PAY_METHOD")
    public String getPayMethod() {
        return payMethod;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PAY_METHOD")
    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.DICTTEXT")
    public String getDicttext() {
        return dicttext;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.DICTTEXT")
    public void setDicttext(String dicttext) {
        this.dicttext = dicttext;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PRINT_DATE")
    public Date getPrintDate() {
        return printDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PRINT_DATE")
    public void setPrintDate(Date printDate) {
        this.printDate = printDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PAYMENT_DATE")
    public Date getPaymentDate() {
        return paymentDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.PAYMENT_DATE")
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.STOP_TRADE_DATE")
    public Date getStopTradeDate() {
        return stopTradeDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.STOP_TRADE_DATE")
    public void setStopTradeDate(Date stopTradeDate) {
        this.stopTradeDate = stopTradeDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.DATA_VERSION")
    public Integer getDataVersion() {
        return dataVersion;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.DATA_VERSION")
    public void setDataVersion(Integer dataVersion) {
        this.dataVersion = dataVersion;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.REIMBURSEMENT_ID")
    public Integer getReimbursementId() {
        return reimbursementId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.REIMBURSEMENT_ID")
    public void setReimbursementId(Integer reimbursementId) {
        this.reimbursementId = reimbursementId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.REFUND_REASON")
    public String getRefundReason() {
        return refundReason;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.REFUND_REASON")
    public void setRefundReason(String refundReason) {
        this.refundReason = refundReason;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.REFUND_REIMBURSEMENT_ID")
    public Integer getRefundReimbursementId() {
        return refundReimbursementId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.REFUND_REIMBURSEMENT_ID")
    public void setRefundReimbursementId(Integer refundReimbursementId) {
        this.refundReimbursementId = refundReimbursementId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.EXCHANGE_METHOD")
    public Integer getExchangeMethod() {
        return exchangeMethod;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.EXCHANGE_METHOD")
    public void setExchangeMethod(Integer exchangeMethod) {
        this.exchangeMethod = exchangeMethod;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.EXCHANGE_LINK")
    public String getExchangeLink() {
        return exchangeLink;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.EXCHANGE_LINK")
    public void setExchangeLink(String exchangeLink) {
        this.exchangeLink = exchangeLink;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.EXCHANGE_CODE")
    public String getExchangeCode() {
        return exchangeCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.EXCHANGE_CODE")
    public void setExchangeCode(String exchangeCode) {
        this.exchangeCode = exchangeCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BI_DATE")
    public Date getBiDate() {
        return biDate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_TRADE_ORDER.BI_DATE")
    public void setBiDate(Date biDate) {
        this.biDate = biDate;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_TRADE_ORDER")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", type=").append(type);
        sb.append(", commodityId=").append(commodityId);
        sb.append(", commodityName=").append(commodityName);
        sb.append(", price=").append(price);
        sb.append(", count=").append(count);
        sb.append(", total=").append(total);
        sb.append(", ofrom=").append(ofrom);
        sb.append(", status=").append(status);
        sb.append(", workerId=").append(workerId);
        sb.append(", workerName=").append(workerName);
        sb.append(", createDate=").append(createDate);
        sb.append(", sellerId=").append(sellerId);
        sb.append(", sellerName=").append(sellerName);
        sb.append(", sellerDeptId=").append(sellerDeptId);
        sb.append(", sellerDeptName=").append(sellerDeptName);
        sb.append(", buyerDeptId=").append(buyerDeptId);
        sb.append(", buyerDeptName=").append(buyerDeptName);
        sb.append(", integral=").append(integral);
        sb.append(", standard=").append(standard);
        sb.append(", recipients=").append(recipients);
        sb.append(", buyerTel=").append(buyerTel);
        sb.append(", buyerAddress=").append(buyerAddress);
        sb.append(", remarks=").append(remarks);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", area=").append(area);
        sb.append(", shopAddr=").append(shopAddr);
        sb.append(", postCompany=").append(postCompany);
        sb.append(", postNo=").append(postNo);
        sb.append(", payDate=").append(payDate);
        sb.append(", deliverDate=").append(deliverDate);
        sb.append(", deliverMsg=").append(deliverMsg);
        sb.append(", receiptDate=").append(receiptDate);
        sb.append(", takeType=").append(takeType);
        sb.append(", isCreateHappy=").append(isCreateHappy);
        sb.append(", payMethod=").append(payMethod);
        sb.append(", dicttext=").append(dicttext);
        sb.append(", printDate=").append(printDate);
        sb.append(", paymentDate=").append(paymentDate);
        sb.append(", stopTradeDate=").append(stopTradeDate);
        sb.append(", dataVersion=").append(dataVersion);
        sb.append(", reimbursementId=").append(reimbursementId);
        sb.append(", refundReason=").append(refundReason);
        sb.append(", refundReimbursementId=").append(refundReimbursementId);
        sb.append(", exchangeMethod=").append(exchangeMethod);
        sb.append(", exchangeLink=").append(exchangeLink);
        sb.append(", exchangeCode=").append(exchangeCode);
        sb.append(", biDate=").append(biDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_TRADE_ORDER")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JhsTradeOrder other = (JhsTradeOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderNo() == null ? other.getOrderNo() == null : this.getOrderNo().equals(other.getOrderNo()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getCommodityId() == null ? other.getCommodityId() == null : this.getCommodityId().equals(other.getCommodityId()))
            && (this.getCommodityName() == null ? other.getCommodityName() == null : this.getCommodityName().equals(other.getCommodityName()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()))
            && (this.getTotal() == null ? other.getTotal() == null : this.getTotal().equals(other.getTotal()))
            && (this.getOfrom() == null ? other.getOfrom() == null : this.getOfrom().equals(other.getOfrom()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getWorkerId() == null ? other.getWorkerId() == null : this.getWorkerId().equals(other.getWorkerId()))
            && (this.getWorkerName() == null ? other.getWorkerName() == null : this.getWorkerName().equals(other.getWorkerName()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getSellerId() == null ? other.getSellerId() == null : this.getSellerId().equals(other.getSellerId()))
            && (this.getSellerName() == null ? other.getSellerName() == null : this.getSellerName().equals(other.getSellerName()))
            && (this.getSellerDeptId() == null ? other.getSellerDeptId() == null : this.getSellerDeptId().equals(other.getSellerDeptId()))
            && (this.getSellerDeptName() == null ? other.getSellerDeptName() == null : this.getSellerDeptName().equals(other.getSellerDeptName()))
            && (this.getBuyerDeptId() == null ? other.getBuyerDeptId() == null : this.getBuyerDeptId().equals(other.getBuyerDeptId()))
            && (this.getBuyerDeptName() == null ? other.getBuyerDeptName() == null : this.getBuyerDeptName().equals(other.getBuyerDeptName()))
            && (this.getIntegral() == null ? other.getIntegral() == null : this.getIntegral().equals(other.getIntegral()))
            && (this.getStandard() == null ? other.getStandard() == null : this.getStandard().equals(other.getStandard()))
            && (this.getRecipients() == null ? other.getRecipients() == null : this.getRecipients().equals(other.getRecipients()))
            && (this.getBuyerTel() == null ? other.getBuyerTel() == null : this.getBuyerTel().equals(other.getBuyerTel()))
            && (this.getBuyerAddress() == null ? other.getBuyerAddress() == null : this.getBuyerAddress().equals(other.getBuyerAddress()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
            && (this.getShopAddr() == null ? other.getShopAddr() == null : this.getShopAddr().equals(other.getShopAddr()))
            && (this.getPostCompany() == null ? other.getPostCompany() == null : this.getPostCompany().equals(other.getPostCompany()))
            && (this.getPostNo() == null ? other.getPostNo() == null : this.getPostNo().equals(other.getPostNo()))
            && (this.getPayDate() == null ? other.getPayDate() == null : this.getPayDate().equals(other.getPayDate()))
            && (this.getDeliverDate() == null ? other.getDeliverDate() == null : this.getDeliverDate().equals(other.getDeliverDate()))
            && (this.getDeliverMsg() == null ? other.getDeliverMsg() == null : this.getDeliverMsg().equals(other.getDeliverMsg()))
            && (this.getReceiptDate() == null ? other.getReceiptDate() == null : this.getReceiptDate().equals(other.getReceiptDate()))
            && (this.getTakeType() == null ? other.getTakeType() == null : this.getTakeType().equals(other.getTakeType()))
            && (this.getIsCreateHappy() == null ? other.getIsCreateHappy() == null : this.getIsCreateHappy().equals(other.getIsCreateHappy()))
            && (this.getPayMethod() == null ? other.getPayMethod() == null : this.getPayMethod().equals(other.getPayMethod()))
            && (this.getDicttext() == null ? other.getDicttext() == null : this.getDicttext().equals(other.getDicttext()))
            && (this.getPrintDate() == null ? other.getPrintDate() == null : this.getPrintDate().equals(other.getPrintDate()))
            && (this.getPaymentDate() == null ? other.getPaymentDate() == null : this.getPaymentDate().equals(other.getPaymentDate()))
            && (this.getStopTradeDate() == null ? other.getStopTradeDate() == null : this.getStopTradeDate().equals(other.getStopTradeDate()))
            && (this.getDataVersion() == null ? other.getDataVersion() == null : this.getDataVersion().equals(other.getDataVersion()))
            && (this.getReimbursementId() == null ? other.getReimbursementId() == null : this.getReimbursementId().equals(other.getReimbursementId()))
            && (this.getRefundReason() == null ? other.getRefundReason() == null : this.getRefundReason().equals(other.getRefundReason()))
            && (this.getRefundReimbursementId() == null ? other.getRefundReimbursementId() == null : this.getRefundReimbursementId().equals(other.getRefundReimbursementId()))
            && (this.getExchangeMethod() == null ? other.getExchangeMethod() == null : this.getExchangeMethod().equals(other.getExchangeMethod()))
            && (this.getExchangeLink() == null ? other.getExchangeLink() == null : this.getExchangeLink().equals(other.getExchangeLink()))
            && (this.getExchangeCode() == null ? other.getExchangeCode() == null : this.getExchangeCode().equals(other.getExchangeCode()))
            && (this.getBiDate() == null ? other.getBiDate() == null : this.getBiDate().equals(other.getBiDate()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_TRADE_ORDER")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderNo() == null) ? 0 : getOrderNo().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getCommodityId() == null) ? 0 : getCommodityId().hashCode());
        result = prime * result + ((getCommodityName() == null) ? 0 : getCommodityName().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        result = prime * result + ((getTotal() == null) ? 0 : getTotal().hashCode());
        result = prime * result + ((getOfrom() == null) ? 0 : getOfrom().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getWorkerId() == null) ? 0 : getWorkerId().hashCode());
        result = prime * result + ((getWorkerName() == null) ? 0 : getWorkerName().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getSellerId() == null) ? 0 : getSellerId().hashCode());
        result = prime * result + ((getSellerName() == null) ? 0 : getSellerName().hashCode());
        result = prime * result + ((getSellerDeptId() == null) ? 0 : getSellerDeptId().hashCode());
        result = prime * result + ((getSellerDeptName() == null) ? 0 : getSellerDeptName().hashCode());
        result = prime * result + ((getBuyerDeptId() == null) ? 0 : getBuyerDeptId().hashCode());
        result = prime * result + ((getBuyerDeptName() == null) ? 0 : getBuyerDeptName().hashCode());
        result = prime * result + ((getIntegral() == null) ? 0 : getIntegral().hashCode());
        result = prime * result + ((getStandard() == null) ? 0 : getStandard().hashCode());
        result = prime * result + ((getRecipients() == null) ? 0 : getRecipients().hashCode());
        result = prime * result + ((getBuyerTel() == null) ? 0 : getBuyerTel().hashCode());
        result = prime * result + ((getBuyerAddress() == null) ? 0 : getBuyerAddress().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getShopAddr() == null) ? 0 : getShopAddr().hashCode());
        result = prime * result + ((getPostCompany() == null) ? 0 : getPostCompany().hashCode());
        result = prime * result + ((getPostNo() == null) ? 0 : getPostNo().hashCode());
        result = prime * result + ((getPayDate() == null) ? 0 : getPayDate().hashCode());
        result = prime * result + ((getDeliverDate() == null) ? 0 : getDeliverDate().hashCode());
        result = prime * result + ((getDeliverMsg() == null) ? 0 : getDeliverMsg().hashCode());
        result = prime * result + ((getReceiptDate() == null) ? 0 : getReceiptDate().hashCode());
        result = prime * result + ((getTakeType() == null) ? 0 : getTakeType().hashCode());
        result = prime * result + ((getIsCreateHappy() == null) ? 0 : getIsCreateHappy().hashCode());
        result = prime * result + ((getPayMethod() == null) ? 0 : getPayMethod().hashCode());
        result = prime * result + ((getDicttext() == null) ? 0 : getDicttext().hashCode());
        result = prime * result + ((getPrintDate() == null) ? 0 : getPrintDate().hashCode());
        result = prime * result + ((getPaymentDate() == null) ? 0 : getPaymentDate().hashCode());
        result = prime * result + ((getStopTradeDate() == null) ? 0 : getStopTradeDate().hashCode());
        result = prime * result + ((getDataVersion() == null) ? 0 : getDataVersion().hashCode());
        result = prime * result + ((getReimbursementId() == null) ? 0 : getReimbursementId().hashCode());
        result = prime * result + ((getRefundReason() == null) ? 0 : getRefundReason().hashCode());
        result = prime * result + ((getRefundReimbursementId() == null) ? 0 : getRefundReimbursementId().hashCode());
        result = prime * result + ((getExchangeMethod() == null) ? 0 : getExchangeMethod().hashCode());
        result = prime * result + ((getExchangeLink() == null) ? 0 : getExchangeLink().hashCode());
        result = prime * result + ((getExchangeCode() == null) ? 0 : getExchangeCode().hashCode());
        result = prime * result + ((getBiDate() == null) ? 0 : getBiDate().hashCode());
        return result;
    }
}