package com.leyoujia.coa.zc.mall.dao.erp.entity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   父子商品表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table JHS_UNITED_COMMODITY
 */
public class JhsUnitedCommodity implements Serializable {
    /**
     * Database Column Remarks:
     *   主键ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.ID")
    private Integer id;

    /**
     * Database Column Remarks:
     *   父商品ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.COMMODITY_PID")
    private Integer commodityPid;

    /**
     * Database Column Remarks:
     *   子商品ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.COMMODITY_SID")
    private Integer commoditySid;

    /**
     * Database Column Remarks:
     *   公费自费类别 0 公费自费 1 仅公费 2 仅自费
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.TYPE")
    private String type;

    /**
     * Database Column Remarks:
     *   唯一性标识,具有相同标识子商品只能购买一个,空或者空字符串不做判断
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.ONLY_ONE")
    private String onlyOne;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.CREATE_TIME")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.UPDATE_TIME")
    private Date updateTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_UNITED_COMMODITY")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.COMMODITY_PID")
    public Integer getCommodityPid() {
        return commodityPid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.COMMODITY_PID")
    public void setCommodityPid(Integer commodityPid) {
        this.commodityPid = commodityPid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.COMMODITY_SID")
    public Integer getCommoditySid() {
        return commoditySid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.COMMODITY_SID")
    public void setCommoditySid(Integer commoditySid) {
        this.commoditySid = commoditySid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.TYPE")
    public String getType() {
        return type;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.TYPE")
    public void setType(String type) {
        this.type = type;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.ONLY_ONE")
    public String getOnlyOne() {
        return onlyOne;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.ONLY_ONE")
    public void setOnlyOne(String onlyOne) {
        this.onlyOne = onlyOne;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.CREATE_TIME")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.CREATE_TIME")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.UPDATE_TIME")
    public Date getUpdateTime() {
        return updateTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: JHS_UNITED_COMMODITY.UPDATE_TIME")
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_UNITED_COMMODITY")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", commodityPid=").append(commodityPid);
        sb.append(", commoditySid=").append(commoditySid);
        sb.append(", type=").append(type);
        sb.append(", onlyOne=").append(onlyOne);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_UNITED_COMMODITY")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JhsUnitedCommodity other = (JhsUnitedCommodity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCommodityPid() == null ? other.getCommodityPid() == null : this.getCommodityPid().equals(other.getCommodityPid()))
            && (this.getCommoditySid() == null ? other.getCommoditySid() == null : this.getCommoditySid().equals(other.getCommoditySid()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getOnlyOne() == null ? other.getOnlyOne() == null : this.getOnlyOne().equals(other.getOnlyOne()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: JHS_UNITED_COMMODITY")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCommodityPid() == null) ? 0 : getCommodityPid().hashCode());
        result = prime * result + ((getCommoditySid() == null) ? 0 : getCommoditySid().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getOnlyOne() == null) ? 0 : getOnlyOne().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}