package com.leyoujia.coa.zc.mall.dao.erp.entity;

import java.io.Serializable;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   部门同步表,与19服务器同步
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SYSTEM_DEPT_BACK
 */
public class SystemDeptBack implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.ID")
    private Integer id;

    /**
     * Database Column Remarks:
     *   部门编号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_NUMBER")
    private String deptNumber;

    /**
     * Database Column Remarks:
     *   部门名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_NAME")
    private String deptName;

    /**
     * Database Column Remarks:
     *   上级部门编号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.ROOTDEPT")
    private String rootdept;

    /**
     * Database Column Remarks:
     *   部门简写
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_SPELL")
    private String deptSpell;

    /**
     * Database Column Remarks:
     *   地址
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.ADDR")
    private String addr;

    /**
     * Database Column Remarks:
     *   状态 Y=正常,N=停用,D=删除
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.STATUS")
    private String status;

    /**
     * Database Column Remarks:
     *   电话
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.PHONE")
    private String phone;

    /**
     * Database Column Remarks:
     *   负责人ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.MANAGER_ID")
    private String managerId;

    /**
     * Database Column Remarks:
     *   负责人姓名
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.MANAGER_NAME")
    private String managerName;

    /**
     * Database Column Remarks:
     *   秘书ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.SECRETARY_ID")
    private String secretaryId;

    /**
     * Database Column Remarks:
     *   秘书姓名
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.SECRETARY_NAME")
    private String secretaryName;

    /**
     * Database Column Remarks:
     *   城市ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.CITY_ID")
    private String cityId;

    /**
     * Database Column Remarks:
     *   店铺ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.SHOP_ID")
    private String shopId;

    /**
     * Database Column Remarks:
     *   对象MD5码
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.BYMD5")
    private String bymd5;

    /**
     * Database Column Remarks:
     *    部门排序
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_NO")
    private String deptNo;

    /**
     * Database Column Remarks:
     *   分成方案 4=商业部 ，其他全部归为住宅
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.COMPUTER_MODE")
    private Integer computerMode;

    /**
     * Database Column Remarks:
     *   公客范围
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.CUST_AREA")
    private Integer custArea;

    /**
     * Database Column Remarks:
     *   部门属性
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_TYPE")
    private String deptType;

    /**
     * Database Column Remarks:
     *   分区主任
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.HR_MANAGER")
    private String hrManager;

    /**
     * Database Column Remarks:
     *   片区主任
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.HR_MANAGER2")
    private String hrManager2;

    /**
     * Database Column Remarks:
     *   所在公司ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_COMP_ID")
    private String deptCompId;

    /**
     * Database Column Remarks:
     *   dep path
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.ID_PATH")
    private String idPath;

    /**
     * Database Column Remarks:
     *   管理区域 无限制: [ALL] CA代表CityArea,CA1代表选择了全部的城区,CA3代表选择了无的城区,LA代表LeafArea
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.MANAGE_AREA")
    private String manageArea;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: SYSTEM_DEPT_BACK")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_NUMBER")
    public String getDeptNumber() {
        return deptNumber;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_NUMBER")
    public void setDeptNumber(String deptNumber) {
        this.deptNumber = deptNumber;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_NAME")
    public String getDeptName() {
        return deptName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_NAME")
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.ROOTDEPT")
    public String getRootdept() {
        return rootdept;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.ROOTDEPT")
    public void setRootdept(String rootdept) {
        this.rootdept = rootdept;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_SPELL")
    public String getDeptSpell() {
        return deptSpell;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_SPELL")
    public void setDeptSpell(String deptSpell) {
        this.deptSpell = deptSpell;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.ADDR")
    public String getAddr() {
        return addr;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.ADDR")
    public void setAddr(String addr) {
        this.addr = addr;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.STATUS")
    public String getStatus() {
        return status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.STATUS")
    public void setStatus(String status) {
        this.status = status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.PHONE")
    public String getPhone() {
        return phone;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.PHONE")
    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.MANAGER_ID")
    public String getManagerId() {
        return managerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.MANAGER_ID")
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.MANAGER_NAME")
    public String getManagerName() {
        return managerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.MANAGER_NAME")
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.SECRETARY_ID")
    public String getSecretaryId() {
        return secretaryId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.SECRETARY_ID")
    public void setSecretaryId(String secretaryId) {
        this.secretaryId = secretaryId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.SECRETARY_NAME")
    public String getSecretaryName() {
        return secretaryName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.SECRETARY_NAME")
    public void setSecretaryName(String secretaryName) {
        this.secretaryName = secretaryName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.CITY_ID")
    public String getCityId() {
        return cityId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.CITY_ID")
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.SHOP_ID")
    public String getShopId() {
        return shopId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.SHOP_ID")
    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.BYMD5")
    public String getBymd5() {
        return bymd5;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.BYMD5")
    public void setBymd5(String bymd5) {
        this.bymd5 = bymd5;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_NO")
    public String getDeptNo() {
        return deptNo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_NO")
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.COMPUTER_MODE")
    public Integer getComputerMode() {
        return computerMode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.COMPUTER_MODE")
    public void setComputerMode(Integer computerMode) {
        this.computerMode = computerMode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.CUST_AREA")
    public Integer getCustArea() {
        return custArea;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.CUST_AREA")
    public void setCustArea(Integer custArea) {
        this.custArea = custArea;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_TYPE")
    public String getDeptType() {
        return deptType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_TYPE")
    public void setDeptType(String deptType) {
        this.deptType = deptType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.HR_MANAGER")
    public String getHrManager() {
        return hrManager;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.HR_MANAGER")
    public void setHrManager(String hrManager) {
        this.hrManager = hrManager;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.HR_MANAGER2")
    public String getHrManager2() {
        return hrManager2;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.HR_MANAGER2")
    public void setHrManager2(String hrManager2) {
        this.hrManager2 = hrManager2;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_COMP_ID")
    public String getDeptCompId() {
        return deptCompId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.DEPT_COMP_ID")
    public void setDeptCompId(String deptCompId) {
        this.deptCompId = deptCompId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.ID_PATH")
    public String getIdPath() {
        return idPath;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.ID_PATH")
    public void setIdPath(String idPath) {
        this.idPath = idPath;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.MANAGE_AREA")
    public String getManageArea() {
        return manageArea;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: SYSTEM_DEPT_BACK.MANAGE_AREA")
    public void setManageArea(String manageArea) {
        this.manageArea = manageArea;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: SYSTEM_DEPT_BACK")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deptNumber=").append(deptNumber);
        sb.append(", deptName=").append(deptName);
        sb.append(", rootdept=").append(rootdept);
        sb.append(", deptSpell=").append(deptSpell);
        sb.append(", addr=").append(addr);
        sb.append(", status=").append(status);
        sb.append(", phone=").append(phone);
        sb.append(", managerId=").append(managerId);
        sb.append(", managerName=").append(managerName);
        sb.append(", secretaryId=").append(secretaryId);
        sb.append(", secretaryName=").append(secretaryName);
        sb.append(", cityId=").append(cityId);
        sb.append(", shopId=").append(shopId);
        sb.append(", bymd5=").append(bymd5);
        sb.append(", deptNo=").append(deptNo);
        sb.append(", computerMode=").append(computerMode);
        sb.append(", custArea=").append(custArea);
        sb.append(", deptType=").append(deptType);
        sb.append(", hrManager=").append(hrManager);
        sb.append(", hrManager2=").append(hrManager2);
        sb.append(", deptCompId=").append(deptCompId);
        sb.append(", idPath=").append(idPath);
        sb.append(", manageArea=").append(manageArea);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: SYSTEM_DEPT_BACK")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SystemDeptBack other = (SystemDeptBack) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDeptNumber() == null ? other.getDeptNumber() == null : this.getDeptNumber().equals(other.getDeptNumber()))
            && (this.getDeptName() == null ? other.getDeptName() == null : this.getDeptName().equals(other.getDeptName()))
            && (this.getRootdept() == null ? other.getRootdept() == null : this.getRootdept().equals(other.getRootdept()))
            && (this.getDeptSpell() == null ? other.getDeptSpell() == null : this.getDeptSpell().equals(other.getDeptSpell()))
            && (this.getAddr() == null ? other.getAddr() == null : this.getAddr().equals(other.getAddr()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getManagerId() == null ? other.getManagerId() == null : this.getManagerId().equals(other.getManagerId()))
            && (this.getManagerName() == null ? other.getManagerName() == null : this.getManagerName().equals(other.getManagerName()))
            && (this.getSecretaryId() == null ? other.getSecretaryId() == null : this.getSecretaryId().equals(other.getSecretaryId()))
            && (this.getSecretaryName() == null ? other.getSecretaryName() == null : this.getSecretaryName().equals(other.getSecretaryName()))
            && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
            && (this.getShopId() == null ? other.getShopId() == null : this.getShopId().equals(other.getShopId()))
            && (this.getBymd5() == null ? other.getBymd5() == null : this.getBymd5().equals(other.getBymd5()))
            && (this.getDeptNo() == null ? other.getDeptNo() == null : this.getDeptNo().equals(other.getDeptNo()))
            && (this.getComputerMode() == null ? other.getComputerMode() == null : this.getComputerMode().equals(other.getComputerMode()))
            && (this.getCustArea() == null ? other.getCustArea() == null : this.getCustArea().equals(other.getCustArea()))
            && (this.getDeptType() == null ? other.getDeptType() == null : this.getDeptType().equals(other.getDeptType()))
            && (this.getHrManager() == null ? other.getHrManager() == null : this.getHrManager().equals(other.getHrManager()))
            && (this.getHrManager2() == null ? other.getHrManager2() == null : this.getHrManager2().equals(other.getHrManager2()))
            && (this.getDeptCompId() == null ? other.getDeptCompId() == null : this.getDeptCompId().equals(other.getDeptCompId()))
            && (this.getIdPath() == null ? other.getIdPath() == null : this.getIdPath().equals(other.getIdPath()))
            && (this.getManageArea() == null ? other.getManageArea() == null : this.getManageArea().equals(other.getManageArea()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: SYSTEM_DEPT_BACK")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDeptNumber() == null) ? 0 : getDeptNumber().hashCode());
        result = prime * result + ((getDeptName() == null) ? 0 : getDeptName().hashCode());
        result = prime * result + ((getRootdept() == null) ? 0 : getRootdept().hashCode());
        result = prime * result + ((getDeptSpell() == null) ? 0 : getDeptSpell().hashCode());
        result = prime * result + ((getAddr() == null) ? 0 : getAddr().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getManagerId() == null) ? 0 : getManagerId().hashCode());
        result = prime * result + ((getManagerName() == null) ? 0 : getManagerName().hashCode());
        result = prime * result + ((getSecretaryId() == null) ? 0 : getSecretaryId().hashCode());
        result = prime * result + ((getSecretaryName() == null) ? 0 : getSecretaryName().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getShopId() == null) ? 0 : getShopId().hashCode());
        result = prime * result + ((getBymd5() == null) ? 0 : getBymd5().hashCode());
        result = prime * result + ((getDeptNo() == null) ? 0 : getDeptNo().hashCode());
        result = prime * result + ((getComputerMode() == null) ? 0 : getComputerMode().hashCode());
        result = prime * result + ((getCustArea() == null) ? 0 : getCustArea().hashCode());
        result = prime * result + ((getDeptType() == null) ? 0 : getDeptType().hashCode());
        result = prime * result + ((getHrManager() == null) ? 0 : getHrManager().hashCode());
        result = prime * result + ((getHrManager2() == null) ? 0 : getHrManager2().hashCode());
        result = prime * result + ((getDeptCompId() == null) ? 0 : getDeptCompId().hashCode());
        result = prime * result + ((getIdPath() == null) ? 0 : getIdPath().hashCode());
        result = prime * result + ((getManageArea() == null) ? 0 : getManageArea().hashCode());
        return result;
    }
}