server:
  port: 8101
  servlet:
    context-path: /coa/zc/mall
    session:
      cookie:
        path: /
spring:
  application:
    name: coa-zc-mall

# 项目配置
coa:
  # session共享
  session:
    redis:
      enable: true
      host: 172.16.4.112
      port: 6379
      database: 0
  mvc:
    login-interceptor:
      enable: true
    operator-resolver:
      enable: true
# log 配置
logging:
  level:
    root: info
    com.leyoujia.coa.zc.mall.MallApplication: info
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: info
    com.leyoujia.coa.zc.core: debug
