# 服务器
server:
    port: 8080
# spring
spring:
    application:
        name: demo
    servlet:
        multipart:
            max-file-size: 30MB
            max-request-size: 50MB
    mvc:
        format:
            # 日期格式
            date: yyyy-MM-dd
            date-time: yyyy-MM-dd HH:mm:ss
            time: HH:mm:ss
# apollo 基础配置
apollo:
    bootstrap:
        # will inject 'application' namespace in bootstrap phase
        enabled: true
          # put apollo initialization before logging system initialization
        eagerLoad:
            enabled: true
        # will inject 'application' namespaces in bootstrap phase
        namespaces: application
# 测试用apollo效果
demo:
    local: local
    # remote: remote
    override: localOverrride
    pp: ${demo.remotepp}
# swagger开关
springfox:
    documentation:
        enabled: true
# 日志
logging:
    file:
        path: ${log_dir:/data/logs}
        name: ${spring.application.name}
    config: classpath:log4j2-spring.xml
